import firebase_admin
from firebase_admin import credentials, firestore
import yfinance as yf
import requests
import zipfile
import io
from bs4 import BeautifulSoup
import datetime
import time
import re
import numpy as np
import pandas as pd
import unittest
import unicodedata
import warnings
import os
import argparse
import json
from bs4 import XMLParsedAsHTMLWarning
warnings.filterwarnings("ignore", category=XMLParsedAsHTMLWarning)

# ==========================================
# ★設定エリア
# ==========================================
EDINET_API_KEY = os.environ.get('EDINET_API_KEY')
FIREBASE_CREDENTIALS = os.environ.get('FIREBASE_CREDENTIALS')
# Firebase認証キーのパスは環境変数またはデフォルトで固定
FIREBASE_KEY = os.environ.get('FIREBASE_KEY_PATH', 'firebase_key.json') 
ALLOW_FULL_FIRESTORE_WRITE = os.environ.get('ALLOW_FULL_FIRESTORE_WRITE') == '1'

# target codes will be dynamically generated by get_all_listed_codes()
# ==========================================

# ==========================================
# 1. B/S マッピング辞書・リスト
# ==========================================
TAG_MAPPING = {
    "CashAndDeposits": "流動_現金及び預金",
    "ElectronicallyRecordedMonetaryClaimsOperating": "流動_電子記録債権",
    "ElectronicallyRecordedMonetaryClaims": "流動_電子記録債権",
    "ElectronicallyRecordedMonetaryClaimsOperatingCA": "流動_電子記録債権",
    "ElectronicallyRecordedMonetaryClaimsTrade": "流動_電子記録債権",
    "NotesReceivableTrade": "流動_受取手形",
    "AccountsReceivableTrade": "流動_売掛金",
    "AccountsReceivable": "流動_売掛金",
    "OperatingAccountsReceivable": "流動_売掛金", 
    "CompletedConstructionContractsReceivable": "流動_売掛金", 
    "NotesAndAccountsReceivableTrade": "流動_受取手形・売掛金(合算)",
    "NotesAndAccountsReceivableTradeAndContractAssets": "流動_受取手形・売掛金(合算)",
    "NotesReceivableAndCompletedConstructionContractsReceivable": "流動_受取手形・売掛金(合算)",
    "NotesAndAccountsReceivable": "流動_受取手形・売掛金(合算)",
    "NotesReceivableAccountsReceivableFromCompletedConstructionContractsAndOtherCNS": "流動_受取手形・売掛金(合算)",
    "NotesAndOperatingAccountsReceivableTradeAndContractAssetsCA": "流動_受取手形・売掛金(合算)",
    "NotesAndOperatingAccountsReceivableCA": "流動_受取手形・売掛金(合算)",
    "NotesAndAccountsReceivableTradeCA": "流動_受取手形・売掛金(合算)",
    "RailwayFaresReceivablesCARWY": "流動_売掛金",
    "AccountsReceivableInstallmentSalesCALEA": "流動_売掛金",
    "ContractAssets": "流動_契約資産",
    "Securities": "流動_有価証券",
    "OperationalInvestmentSecurities": "流動_有価証券",
    "MerchandiseAndFinishedGoods": "流動_棚卸資産",
    "WorkInProcess": "流動_棚卸資産",
    "RawMaterialsAndSupplies": "流動_棚卸資産",
    "FinishedGoods": "流動_棚卸資産",
    "Merchandise": "流動_棚卸資産",
    "Supplies": "流動_棚卸資産",
    "Inventories": "流動_棚卸資産",
    "RealEstateForSale": "流動_棚卸資産",
    "RealEstateForSaleInProcess": "流動_棚卸資産",
    "LandAndBuildingsForSaleInLots": "流動_棚卸資産",
    "LandForDevelopment": "流動_棚卸資産",
    "ExpenditureOnContractsInProgress": "流動_棚卸資産",
    "OtherInventories": "流動_棚卸資産",
    "EquityInvestmentsInPropertiesForSale": "流動_棚卸資産",
    "CostsOnRealEstateBusiness": "流動_棚卸資産",
    "CostsOnUncompletedConstructionContracts": "流動_棚卸資産",
    "PrepaidExpenses": "流動_前払費用",
    "DeferredAndPrepaidExpensesCAWAT": "流動_前払費用",
    "AdvancePaymentsTrade": "流動_前渡金",
    "ConsumptionTaxesReceivable": "流動_未収消費税等",
    "IncomeTaxesReceivable": "流動_その他流動資産",
    "ShortTermLoansReceivable": "流動_短期貸付金",
    "OperatingLoansCA": "流動_金融債権",
    "CurrentPortionOfLongTermLoansReceivableFromSubsidiariesAndAffiliates": "流動_短期貸付金",
    "AccountsReceivableOther": "流動_未収入金",
    "AccruedIncome": "流動_未収入金",
    "LeaseReceivablesAndInvestmentsInLeases": "流動_リース債権",
    "LeaseInvestmentAssetsCA": "流動_リース債権",
    "LeaseReceivablesCA": "流動_リース債権",
    "LeaseReceivablesAndInvestmentAssetsCA": "流動_リース債権",
    "MoneyHeldInTrustForTheChuoShinkansenConstructionCA": "流動_その他金融資産",
    "OtherCurrentAssets": "流動_その他流動資産", "OtherCA": "流動_その他流動資産",
    "AllowanceForDoubtfulAccountsCurrent": "流動_貸倒引当金", "AllowanceForDoubtfulAccountsCA": "流動_貸倒引当金",
    "BuildingsAndStructures": "有形_建物・構築物", "BuildingsAndStructuresNet": "有形_建物・構築物",
    "Buildings": "有形_建物・構築物", "Structures": "有形_建物・構築物",
    "MachineryEquipmentAndVehicles": "有形_機械・運搬具", "MachineryEquipmentAndVehiclesNet": "有形_機械・運搬具",
    "MachineryAndEquipment": "有形_機械・運搬具",
    "VehiclesAndDeliveryEquipment": "有形_機械・運搬具", "VehiclesAndDeliveryEquipmentNet": "有形_機械・運搬具",
    "Land": "有形_土地",
    "ConstructionInProgress": "有形_建設仮勘定",
    "ConstructionInProgressELE": "有形_建設仮勘定",
    "ConstructionAndRetirementInProgressNCAInProcessELE": "有形_建設仮勘定",
    "NuclearPowerAbolitionInProgressELE": "有形_建設仮勘定",
    "LeaseAssets": "有形_リース資産", "LeaseAssetsNet": "有形_リース資産",
    "LeaseAssetsPPE": "有形_リース資産", "LeaseAssetsNetPPE": "有形_リース資産",
    "AssetsForOperatingLeases": "有形_賃貸用資産", "AssetsForOperatingLeasesNet": "有形_賃貸用資産",
    "PropertyForLeasePPELEA": "有形_賃貸用資産",
    "AdvancesForPurchasesAtLeasedAssetsPPELEA": "有形_賃貸用資産",
    "ToolsFurnitureAndFixtures": "有形_工具器具備品", "ToolsFurnitureAndFixturesNet": "有形_工具器具備品",
    "FurnitureAndFixturesNetPPE": "有形_工具器具備品",
    "OtherPropertyPlantAndEquipment": "有形_その他有形固定資産", "OtherPropertyPlantAndEquipmentNet": "有形_その他有形固定資産", "OtherNetPPE": "有形_その他有形固定資産",
    "BuildingsNet": "有形_建物・構築物",
    "VesselsNet": "有形_その他有形固定資産", "AircraftNet": "有形_その他有形固定資産", "EquipmentNetPPEWAT": "有形_その他有形固定資産",
    "ElectricUtilityPlantAndEquipmentAssetsELE": "有形_その他有形固定資産",
    "DistributionFacilitiesNCAElectricELE": "有形_その他有形固定資産",
    "TransmissionFacilitiesNCAElectricELE": "有形_その他有形固定資産",
    "TransformationFacilitiesNCAElectricELE": "有形_その他有形固定資産",
    "HydroelectricPowerProductionFacilitiesNCAElectricELE": "有形_その他有形固定資産",
    "ThermalPowerProductionFacilitiesNCAElectricELE": "有形_その他有形固定資産",
    "NuclearPowerProductionFacilitiesNCAElectricELE": "有形_その他有形固定資産",
    "GeneralFacilitiesNCAElectricELE": "有形_その他有形固定資産",
    "OtherElectricUtilityPlantAndEquipmentNCAElectricELE": "有形_その他有形固定資産",
    "OtherPPE": "有形_その他有形固定資産",
    "Software": "無形_ソフトウエア", "Goodwill": "無形_のれん", "LeaseholdRight": "無形_借地権", "TelephoneSubscriptionRight": "無形_その他無形固定資産", "OtherIntangibleAssets": "無形_その他無形固定資産", "OtherIA": "無形_その他無形固定資産",
    "InvestmentSecurities": "投資_投資有価証券", "InvestmentsInCapital": "投資_投資有価証券", "SharesOfSubsidiariesAndAssociates": "投資_関係会社株式",
    "StocksOfSubsidiariesAndAffiliates": "投資_関係会社株式",
    "InvestmentsInOtherSecuritiesOfSubsidiariesAndAffiliates": "投資_関係会社株式",
    "InvestmentsInCapitalOfSubsidiariesAndAffiliates": "投資_関係会社株式",
    "LongTermInvestmentForSubsidiariesAndAffiliatesELE": "投資_関係会社株式",
    "DeferredTaxAssets": "投資_繰延税金資産", "DeferredTaxAssetsForLandRevaluation": "投資_繰延税金資産", "RetirementBenefitAsset": "投資_退職給付資産",
    "NetDefinedBenefitAsset": "投資_退職給付資産",
    "InvestmentProperty": "投資_投資不動産", "LongTermLoansReceivable": "投資_長期貸付金",
    "LongTermLoansReceivableFromSubsidiariesAndAffiliates": "投資_長期貸付金",
    "LeaseDeposits": "投資_差入保証金", "LeaseAndGuaranteeDeposits": "投資_差入保証金", "PrepaidPensionCostIOA": "投資_退職給付資産", "DeferredAssets": "投資_その他固定資産", "BondIssuanceCostDA": "投資_その他固定資産", "LongTermPrepaidExpenses": "投資_その他固定資産", "MoneyHeldInTrustIOA": "投資_その他金融資産", "LongTermInvestmentsELE": "投資_投資有価証券", "ReserveFundForNuclearReactorDecommissioningIOAELE": "投資_その他固定資産", "NuclearFuelNCAELE": "投資_その他固定資産", "NuclearFuelInProcessingNCAELE": "投資_その他固定資産", "LoadedNuclearFuelNCAELE": "投資_その他固定資産", "SpecialAccountRelatedToReprocessingOfSpentNuclearFuelELE": "投資_その他固定資産", "GrantsInAidReceivableFromNuclearDamageCompensationFacilitationCorporationIOAELE": "投資_その他固定資産", "OtherNoncurrentAssetsELE": "投資_その他固定資産", "OtherInvestmentsAndOtherAssets": "投資_その他固定資産", "OtherIOA": "投資_その他固定資産", "ClaimsProvableInBankruptcyClaimsProvableInRehabilitationAndOther": "投資_その他固定資産",
    "AllowanceForDoubtfulAccountsNonCurrent": "投資_貸倒引当金", "AllowanceForDoubtfulAccountsIOAByGroup": "投資_貸倒引当金",
    "NotesAndAccountsPayableTrade": "流負_支払手形・買掛金",
    "NotesAndOperatingAccountsPayableTrade": "流負_支払手形・買掛金",
    "AccountsPayableTrade": "流負_支払手形・買掛金",
    "ElectronicallyRecordedObligationsOperating": "流負_支払手形・買掛金", 
    "OperatingAccountsPayable": "流負_支払手形・買掛金",
    "NotesPayableAccountsPayableForConstructionContractsAndOtherCNS": "流負_支払手形・買掛金",
    "ShortTermLoansPayable": "流負_短期借入金", "ShortTermLoansPayableToSubsidiariesAndAffiliates": "流負_短期借入金", "ShortTermNonRecourseLoansCL": "流負_短期ノンリコース借入金", "CurrentPortionOfLongTermLoansPayable": "流負_1年内返済長期借入金",
    "CurrentPortionOfLongTermLoansPayableToSubsidiariesAndAffiliates": "流負_1年内返済長期借入金",
    "CurrentPortionOfBonds": "流負_1年内償還社債", "ShortTermBondsPayable": "流負_1年内償還社債", "NonRecourseBondsDueWithinOneYearCL": "流負_1年内償還ノンリコース社債", "CommercialPapersLiabilities": "流負_CP",
    "AccountsPayableOther": "流負_未払金", "AccruedExpenses": "流負_未払費用",
    "AccruedConsumptionTaxes": "流負_未払費用",
    "IncomeTaxesPayable": "流負_未払法人税等", "AdvancesReceived": "流負_前受金",
    "UnearnedRevenue": "流負_前受金",
    "AdvancesReceivedOnUncompletedConstructionContracts": "流負_前受金", "ContractLiabilities": "流負_前受金",
    "AdvancesReceivedOnUncompletedConstructionContractsCNS": "流負_前受金", "PrepaidFaresReceivedCLRWY": "流負_前受金", "InterLineFaresReceivedCLRWY": "流負_前受金", "DepositsReceived": "流負_預り金",
    "LeaseObligationsCurrent": "流負_リース債務", "LeaseObligationsCL": "流負_リース債務", "ProvisionForBonuses": "流負_賞与引当金",
    "ProvisionForShareBasedRemunerationCL": "流負_引当金",
    "ProvisionForShareBasedPaymentsCL": "流負_引当金",
    "OtherProvisionCL": "流負_引当金",
    "ProvisionForLossOnGuaranteesCL": "流負_引当金",
    "ProvisionForLossOnContractsCL": "流負_引当金",
    "ProvisionForLossOnContractCL": "流負_引当金",
    "ProvisionForDirectorsBonuses": "流負_賞与引当金",
    "ProvisionForWarrantiesForCompletedConstruction": "流負_引当金",
    "ReserveForStocksPaymentLiabilities": "流負_その他流動負債",
    "DeferredProfitOnInstallmentSalesCLLEA": "流負_その他流動負債",
    "AccruedTaxes": "流負_その他流動負債",
    "CurrentPortionOfLongTermAccountsPayableRailwayEquipmentCLRWY": "流負_その他流動負債",
    "CurrentPortionOfNoncurrentLiabilitiesCLELE": "流負_その他流動負債",
    "OtherCurrentLiabilities": "流負_その他流動負債", "OtherCL": "流負_その他流動負債",
    "BondsPayable": "固負_社債", "ConvertibleBondTypeBondsWithSubscriptionRightsToShares": "固負_社債",
    "LongTermLoansPayable": "固負_長期借入金", "LongTermLoansPayableToSubsidiariesAndAffiliates": "固負_長期借入金", "LongTermDebtForTheChuoShinkansenConstructionNCL": "固負_長期借入金", "LongTermNonRecourseLoansNCL": "固負_長期ノンリコース借入金", "DeferredTaxLiabilities": "固負_繰延税金負債", "DeferredTaxLiabilitiesForLandRevaluation": "固負_繰延税金負債",
    "RetirementBenefitLiability": "固負_退職給付引当金", "NetDefinedBenefitLiability": "固負_退職給付引当金",
    "LeaseObligationsNonCurrent": "固負_リース債務", "LeaseObligationsNCL": "固負_リース債務", "AssetRetirementObligations": "固負_資産除去債務", "AssetRetirementObligationsNCL": "固負_資産除去債務",
    "ProvisionForDirectorsRetirementBenefits": "固負_その他固定負債",
    "ProvisionForShareBasedRemunerationNCL": "固負_その他固定負債",
    "ProvisionForRetirementBenefits": "固負_退職給付引当金",
    "ProvisionForSpecialRepairsNCLWAT": "固負_引当金",
    "ProvisionForLossOnContractsNCL": "固負_引当金",
    "ProvisionForLossOnContractNCL": "固負_引当金",
    "ProvisionForShareBasedPaymentsNCL": "固負_引当金",
    "ProvisionForLossOnGuarantees": "固負_引当金",
    "OtherProvisionNCL": "固負_引当金",
    "ProvisionForLossOnDisasterNCL": "固負_その他固定負債",
    "ProvisionForLargeScaleRenovationOfTheShinkansenInfrastructureNCLRWY": "固負_その他固定負債",
    "ContributionPayableForNuclearReactorDecommissioningNCLELE": "固負_その他固定負債",
    "ProvisionForCompensationForNuclearPowerRelatedDamagesNCLELE": "固負_その他固定負債",
    "ProvisionForPreparationOfRemovalOfReactorCoresInSpecifiedNuclearPowerFacilitiesNCLELE": "固負_その他固定負債",
    "ProvisionForRemovalOfReactorCoresInSpecifiedNuclearPowerFacilitiesNCLELE": "固負_その他固定負債",
    "ReservesUnderTheSpecialLaws2": "固負_その他固定負債",
    "ReserveForFluctuationInWaterLevelsReservesUnderTheSpecialLawsELE": "固負_その他固定負債",
    "NonCurrentLeaseObligationOtherLiabilities": "固負_リース債務",
    "LongTermIncomeTaxesPayable": "固負_その他固定負債",
    "FundForPriceFluctuationAllowance": "固負_その他固定負債",
    "ReserveForVariableCompensation": "固負_その他固定負債",
    "SustainableEnergySubsidyIFRS": "固負_その他固定負債",
    "LongTermDepositsReceived": "固負_長期預り金", "LongTermGuaranteeDeposited": "固負_長期預り金", "LeaseAndGuaranteeDepositsReceived": "固負_長期預り金", "LongTermAccountsPayableRailwayEquipmentNCLRWY": "固負_その他固定負債", "OtherNonCurrentLiabilities": "固負_その他固定負債", "OtherNCL": "固負_その他固定負債",
    "NonRecourseBondsNCL": "固負_ノンリコース社債",
    "CapitalStock": "純資_資本金", "CapitalSurplus": "純資_資本剰余金",
    "RetainedEarnings": "純資_利益剰余金", "LegalRetainedEarnings": "純資_利益剰余金", "TreasuryShares": "純資_自己株式", "TreasuryStock": "純資_自己株式",
    "ValuationAndTranslationAdjustments": "純資_評価換算差額金",
    "OtherComprehensiveIncomeRelatedToAssetsHeldForSaleIFRS": "純資_評価換算差額金",
    "OtherComprehensiveIncomeRelatedToAssetsHeldForSaleEquityAttributableToOwnersOfParentIFRS": "純資_評価換算差額金",
    "ExchangeDifferencesOnTranslationOfForeignOperationsEquityIFRS": "純資_評価換算差額金",
    "EffectivePortionOfCashFlowHedgesEquityIFRS": "純資_評価換算差額金",
    "RemeasurementsOfDefinedBenefitPlans": "純資_評価換算差額金",
    "RevaluationReserveForLand": "純資_評価換算差額金",
    "NonControllingInterests": "純資_非支配株主持分", "SubscriptionRightsToShares": "純資_新株予約権",
    # J-GAAP 短期有価非(流動資産に記載)
    "ShortTermInvestmentSecurities": "流動_有価証券",
    
    # === IFRS 追加タグ ===
    "CashAndCashEquivalents": "流動_現金及び預金",
    "TradeAndOtherCurrentReceivables": "流動_売掛金",
    "OtherCurrentFinancialAssets": "流動_その他金融資産",
    "ShorttermFinancialAssets": "流動_有価証券",
    "OtherFinancialAssetsCurrent": "流動_その他金融資産",
    "IntangibleAssetsOtherThanGoodwill": "無形_その他無形固定資産",
    "IntangibleAssets": "無形_その他無形固定資産",
    "InvestmentsAccountedForUsingEquityMethod": "投資_関係会社株式",
    "InvestmentsInAssociatesAndJointVentures": "投資_関係会社株式",
    "OtherNoncurrentFinancialAssets": "投資_その他金融資産",
    "OtherFinancialAssetsNoncurrent": "投資_その他金融資産",
    "TradeAndOtherCurrentPayables": "流負_支払手形・買掛金",
    "TradeAndOtherPayables": "流負_支払手形・買掛金",
    "BondsAndBorrowingsCurrent": "流負_短期借入金",
    "ShorttermBorrowings": "流負_短期借入金",
    "OtherCurrentFinancialLiabilities": "流負_その他金融負債",
    "OtherFinancialLiabilitiesCurrent": "流負_その他金融負債",
    "BondsAndBorrowingsNoncurrent": "固負_長期借入金",
    "LongtermBorrowings": "固負_長期借入金",
    "OtherNoncurrentFinancialLiabilities": "固負_その他金融負債",
    "OtherFinancialLiabilitiesNoncurrent": "固負_その他金融負債",

    # === IFRS 固有/四半期 (jpigp_cor, jpcrp_cor) 追加タグ ===
    "CashAndCashEquivalentsIFRS": "流動_現金及び預金",
    "TradeAndOtherCurrentReceivablesIFRS": "流動_売掛金",
    "TradeAndOtherReceivablesCAIFRS": "流動_売掛金",
    "TradeAndOtherReceivables2CAIFRS": "流動_売掛金",
    "TradeReceivablesOtherReceivablesAndContractAssetsCAIFRS": "流動_売掛金",
    "TradeReceivablesCAIFRS": "流動_売掛金",
    "TradeReceivablesAndContractAssetsCAIFRSIFRS": "流動_売掛金",
    "TradeAndOtherReceivablesNCAIFRS": "投資_長期営業債権",
    "ReceivablesRelatedToFinancialServicesCAIFRS": "流動_金融債権",
    "ReceivablesRelatedToFinancialServicesNCAIFRS": "投資_金融債権",
    "InventoriesIFRS": "流動_棚卸資産",
    "InventoriesCAIFRS": "流動_棚卸資産",
    "MerchandiseAndFinishedGoodsCAIFRS": "流動_棚卸資産",
    "FinishedGoodsCAIFRS": "流動_棚卸資産",
    "SemiFinishedGoodsAndWorkInProcessCAIFRS": "流動_棚卸資産",
    "WorkInProcessCAIFRS": "流動_棚卸資産",
    "RawMaterialsCAIFRS": "流動_棚卸資産",
    "RawMaterialsWorkInProgressAndSuppliesCAIFRS": "流動_棚卸資産",
    "RawMaterialsPurchasedComponentsAndSuppliesCAIFRS": "流動_棚卸資産",
    "RawMaterialsAndSuppliesCAIFRS": "流動_棚卸資産",
    "SuppliesAndOtherCAIFRS": "流動_棚卸資産",
    "ProductionSuppliesCAIFRS": "流動_棚卸資産",
    "TelecommunicationsTerminalEquipmentAndMaterialsToBeSoldCAIFRS": "流動_棚卸資産",
    "RealEstateForSaleCAIFRS": "流動_棚卸資産",
    "OtherInventoriesCAIFRS": "流動_棚卸資産",
    "BiologicalAssetsCAIFRS": "流動_生物資産",
    "AdvancePaymentsToSuppliersCAIFRS": "流動_前渡金",
    "OtherCurrentFinancialAssetsCAIFRS": "流動_その他金融資産",
    "OtherFinancialAssetsCAIFRS": "流動_その他金融資産",
    "DerivativeAssetsCAIFRS": "流動_その他金融資産",
    "TimeDepositsCAIFRS": "流動_その他金融資産",
    "ShortTermLoansForBankingCAIFRS": "流動_金融債権",
    "AssetsHeldForSaleIFRS": "流動_売却目的保有資産",
    "OtherCurrentAssetsCAIFRS": "流動_その他流動資産",
    "IncomeTaxesReceivableCAIFRS": "流動_その他流動資産",
    # IFRS 有形固定資産
    "PropertyPlantAndEquipmentIFRS": "有形_その他有形固定資産",
    "BuildingsAndAccompanyingFacilitiesIFRS": "有形_建物・構築物",
    "BuildingsAndStructuresIFRS": "有形_建物・構築物",
    "MachineryAndEquipmentIFRS": "有形_機械・運搬具",
    "MachineryAndVehiclesIFRS": "有形_機械・運搬具",
    "MachineryandequipmentIFRS": "有形_機械・運搬具",
    "MachineryVesselsAndToolsIFRS": "有形_機械・運搬具",
    "TelecommunicationsEquipmentIFRS": "有形_通信設備",
    "TelecommunicationsServiceLinesIFRS": "有形_通信線路",
    "MineralResourcesRelatedPropertyIFRS": "有形_その他有形固定資産",
    "LandIFRS": "有形_土地",
    "ConstructionInProgressIFRS": "有形_建設仮勘定",
    "RightOfUseAssetsIFRS": "有形_リース資産",
    "RightsToUseFacilitiesIFRS": "有形_リース資産",
    "FurnitureAndFixturesIFRS": "有形_工具器具備品",
    "ToolsFurnitureAndFixturesIFRS": "有形_工具器具備品",
    "AircraftAndShipsIFRS": "有形_その他有形固定資産",
    "OtherComponentsOfPropertyPlantAndEquipmentIFRS": "有形_その他有形固定資産",
    # IFRS 無形固定資産
    "IntangibleAssetsIFRS": "無形_その他無形固定資産",
    "GoodwillIFRS": "無形_のれん",
    "GoodwillAndIntangibleAssetsIFRS": "無形_その他無形固定資産",
    "CustomerRelatedAssetsIFRS": "無形_その他無形固定資産",
    "TechnologyBasedIntangibleAssetsIFRS": "無形_その他無形固定資産",
    "SoftwareIFRS": "無形_ソフトウエア",
    "SoftwareForInternalUseIFRS": "無形_ソフトウエア",
    "SoftwareForSaleIFRS": "無形_ソフトウエア",
    "CapitalizedDevelopmentCostsIFRS": "無形_その他無形固定資産",
    "CapitalizedDevelopmentCosts2IFRS": "無形_その他無形固定資産",
    "CustomerRelationshipsIFRS": "無形_その他無形固定資産",
    "TechnologiesIFRS": "無形_その他無形固定資産",
    "TrademarksIntangibleAssetsWithIndefiniteUsefulLivesIFRS": "無形_その他無形固定資産",
    "TrademarksIFRS": "無形_その他無形固定資産",
    "MusicCatalogsIFRS": "無形_その他無形固定資産",
    "FilmCostIFRS": "無形_その他無形固定資産",
    "ContentAssetsNCAIFRS": "無形_その他無形固定資産",
    "BroadcastingRightsIFRS": "無形_その他無形固定資産",
    "GameContentIFRS": "無形_その他無形固定資産",
    "IntangibleAssetsAssociatedWithProductsIFRS": "無形_その他無形固定資産",
    "OtherComponentsOfIntangibleAssetsIFRS": "無形_その他無形固定資産",
    "FishFarmingLicenseAndSurfaceRightsIFRS": "無形_その他無形固定資産",
    "OtherIntangibleAssetsIFRS": "無形_その他無形固定資産",
    "OtherIntangibleAssetsWithFiniteUsefulLivesIFRS": "無形_その他無形固定資産",
    "OtherIntangibleAssetsWithIndefiniteUsefulLivesIFRS": "無形_その他無形固定資産",
    "SpectrumMigrationCostsIFRS": "無形_その他無形固定資産",
    "ArtistContractsIFRS": "無形_その他無形固定資産",
    "MusicDistributionRightsIFRS": "無形_その他無形固定資産",
    "PatentRightsKnowHowAndLicenseAgreementsIFRS": "無形_その他無形固定資産",
    "TelevisionCarriageContractsIFRS": "無形_その他無形固定資産",
    # IFRS 投資その他
    "InvestmentsAccountedForUsingEquityMethodIFRS": "投資_関係会社株式",
    "InvestmentsInSecuritiesAndOtherFinancialAssetsNCAIFRS": "投資_投資有価証券",
    "InvestmentsInSecuritiesAndOtherFinancialAssetsCAIFRS": "流動_有価証券",
    "InvestmentSecuritiesNCAIFRS": "投資_投資有価証券",
    "InvestmentsFromSVFFVTPLNCAIFRS": "投資_SVF投資",
    "OtherInvestmentsIFRS": "投資_投資有価証券",
    "FinancialAssetsMeasuredAtFairValueNCAIFRS": "投資_その他金融資産",
    "FinancialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncomeEquityIFRS": "投資_投資有価証券",
    "SecuritiesForBankingNCAIFRS": "投資_その他金融資産",
    "LongTermLoansForBankingNCAIFRS": "投資_金融債権",
    "OtherFinancialAssetsNCAIFRS": "投資_その他金融資産",
    "DerivativeAssetsNCAIFRS": "投資_その他金融資産",
    "LongTermDepositsForBankingNCLIFRS": "投資_その他金融資産",
    "CostsToObtainContractsNCAIFRS": "投資_契約獲得コスト",
    "OtherNonCurrentAssetsNCAIFRS": "投資_その他固定資産",
    "InvestmentPropertyIFRS": "投資_投資不動産",
    "RetirementBenefitAssetNCAIFRS": "投資_退職給付資産",
    "DeferredTaxAssetsIFRS": "投資_繰延税金資産",
    # IFRS 流動負債
    "TradeAndOtherCurrentPayablesIFRS": "流負_支払手形・買掛金",
    "TradeAndOtherCurrentPayablesCLIFRS": "流負_支払手形・買掛金",
    "TradeAndOtherPayablesCLIFRS": "流負_支払手形・買掛金",
    "TradeAndOtherPayables2CLIFRS": "流負_支払手形・買掛金",
    "TradePayables3CLIFRS": "流負_支払手形・買掛金",
    "TradePayablesCLIFRS": "流負_支払手形・買掛金",
    "InterestBearingLiabilitiesCLIFRS": "流負_短期借入金",
    "BorrowingsCLIFRS": "流負_短期借入金",
    "BondsAndBorrowingsCLIFRS": "流負_短期借入金",
    "ShortTermDebtCLIFRS": "流負_短期借入金",
    "CurrentPortionOfLongTermDebtCLIFRS": "流負_1年内返済長期借入金",
    "IncomeTaxesPayableCLIFRS": "流負_未払法人税等",
    "AccruedExpensesCLIFRS": "流負_未払費用",
    "AccruedPayrollCLIFRS": "流負_未払費用",
    "ContractLiabilitiesCLIFRS": "流負_前受金",
    "AdvancesReceivedCLIFRS": "流負_前受金",
    "DepositsForBankingBusinessCLIFRS": "流負_銀行預金",
    "ShortTermDepositsForBankingCLIFRS": "流負_銀行預金",
    "LeaseLiabilitiesCLIFRS": "流負_リース債務",
    "ProvisionsCLIFRS": "流負_引当金",
    "ProvisonsForCustomerLoyaltyProgramCLIFRS": "流負_引当金",
    "LiabilitiesForQualityAssuranceCLIFRS": "流負_製品保証負債",
    "OtherFinancialLiabilitiesCLIFRS": "流負_その他金融負債",
    "LiabilitiesDirectlyAssociatedWithAssetsHeldForSaleIFRS": "流負_売却目的保有関連負債",
    "DerivativeLiabilitiesCLIFRS": "流負_デリバティブ負債",
    "OtherCurrentLiabilitiesCLIFRS": "流負_その他流動負債",
    "ParticipationLiabilitiesInThePicturesSegmentCLIFRS": "流負_映画分野参加負債",
    # IFRS 固定負債
    "InterestBearingLiabilitiesNCLIFRS": "固負_長期借入金",
    "BondsAndBorrowingsNCLIFRS": "固負_長期借入金",
    "BorrowingsNCLIFRS": "固負_長期借入金",
    "LongTermDebtNCLIFRS": "固負_長期借入金",
    "LongTermDebt2NCLIFRS": "固負_長期借入金",
    "LongTermDebtIFRSNCLIFRS": "固負_長期借入金",
    "RetirementBenefitLiabilityNCLIFRS": "固負_退職給付引当金",
    "DefinedBenefitLiabilityNCLIFRS": "固負_退職給付引当金",
    "LeaseLiabilitiesNCLIFRS": "固負_リース債務",
    "ProvisionsNCLIFRS": "固負_引当金",
    "ThirdPartyInterestsInSVFNCLIFRS": "固負_SVF外部持分",
    "DerivativeLiabilitiesNCLIFRS": "固負_デリバティブ負債",
    "TradeAndOtherPayablesNCLIFRS": "固負_その他金融負債",
    "OtherFinancialLiabilitiesNCLIFRS": "固負_その他金融負債",
    "OtherNonCurrentLiabilitiesNCLIFRS": "固負_その他固定負債",
    "ParticipationLiabilitiesInThePicturesSegmentNCLIFRS": "固負_映画分野参加負債",
    "DeferredTaxLiabilitiesIFRS": "固負_繰延税金負債",
    # IFRS 純資産
    "ShareCapitalIFRS": "純資_資本金",
    "CapitalSurplusIFRS": "純資_資本剰余金",
    "RetainedEarningsIFRS": "純資_利益剰余金",
    "TreasurySharesIFRS": "純資_自己株式",
    "AccumulatedOtherComprehensiveIncomeIFRS": "純資_評価換算差額金",
    "OtherComponentsOfEquityIFRS": "純資_評価換算差額金",
    "NonControllingInterestsIFRS": "純資_非支配株主持分",

    # === US GAAP 追加タグ ===
    "CashAndCashEquivalentsAtCarryingValue": "流動_現金及び預金",
    "CashAndCashEquivalentsUSGAAPSummaryOfBusinessResults": "流動_現金及び預金",
    "AccountsReceivableNetCurrent": "流動_売掛金",
    "ReceivablesNetCurrent": "流動_売掛金",
    "InventoryNet": "流動_棚卸資産",
    "OtherAssetsCurrent": "流動_その他流動資産",
    "IntangibleAssetsNetExcludingGoodwill": "無形_その他無形固定資産",
    "GoodwillUSGAAP": "無形_のれん",
    "OtherAssetsNoncurrent": "投資_その他固定資産",
    "EquityMethodInvestments": "投資_関係会社株式",
    "AccountsPayableCurrent": "流負_支払手形・買掛金",
    "ShortTermBorrowings": "流負_短期借入金",
    "OtherLiabilitiesCurrent": "流負_その他流動負債",
    "LongTermDebtNoncurrent": "固負_長期借入金",
    "OtherLiabilitiesNoncurrent": "固負_その他固定負債",
    "EquityAttributableToOwnersOfParentUSGAAPSummaryOfBusinessResults": "純資_利益剰余金",
}


DISPLAY_ORDER = [
    "流動_現金及び預金", "流動_受取手形", "流動_売掛金", "流動_契約資産", "流動_電子記録債権", "流動_受取手形・売掛金(合算)", 
    "流動_有価証券", "流動_棚卸資産", "流動_生物資産", "流動_前払費用", "流動_前渡金", "流動_未収入金", "流動_未収消費税等", "流動_短期貸付金", "流動_リース債権",
    "流動_貸倒引当金", "流動_金融債権", "流動_その他金融資産", "流動_売却目的保有資産", "流動_その他流動資産",
    "有形_建物・構築物", "有形_機械・運搬具", "有形_通信設備", "有形_通信線路", "有形_土地", "有形_建設仮勘定", "有形_リース資産", "有形_賃貸用資産", "有形_工具器具備品", "有形_その他有形固定資産",
    "無形_ソフトウエア", "無形_のれん", "無形_借地権", "無形_その他無形固定資産",
    "投資_投資有価証券", "投資_SVF投資", "投資_関係会社株式", "投資_投資不動産", "投資_金融債権", "投資_長期営業債権", "投資_その他金融資産", "投資_長期貸付金", "投資_差入保証金", "投資_退職給付資産", "投資_繰延税金資産", "投資_契約獲得コスト", "投資_貸倒引当金", "投資_その他固定資産",
    "流負_支払手形・買掛金", "流負_短期借入金", "流負_1年内返済長期借入金", "流負_1年内償還社債", "流負_CP",
    "流負_未払金", "流負_未払費用", "流負_未払法人税等", "流負_前受金", "流負_預り金", "流負_銀行預金", "流負_リース債務", "流負_賞与引当金", "流負_短期ノンリコース借入金", "流負_1年内償還ノンリコース社債", "流負_引当金", "流負_製品保証負債", "流負_その他金融負債", "流負_デリバティブ負債", "流負_売却目的保有関連負債", "流負_映画分野参加負債", "流負_その他流動負債",
    "固負_社債", "固負_ノンリコース社債", "固負_長期借入金", "固負_長期ノンリコース借入金", "固負_リース債務", "固負_退職給付引当金", "固負_資産除去債務", "固負_長期預り金", "固負_繰延税金負債", "固負_引当金", "固負_その他金融負債", "固負_SVF外部持分", "固負_デリバティブ負債", "固負_映画分野参加負債", "固負_その他固定負債",
    "純資_資本金", "純資_資本剰余金", "純資_利益剰余金", "純資_自己株式", "純資_評価換算差額金", "純資_新株予約権", "純資_非支配株主持分", "純資_その他純資産"
]

# ==========================================
# 2. 書類検索クラス
# ==========================================
class EdinetSearcher:
    def __init__(self):
        self.df_docs = pd.DataFrame()

    def fetch_list(self, target_codes, days_back=365):
        today = datetime.date.today()
        print(f"--- [リスト作成] 最大 {days_back} 日分をスキャンします（対象書類が揃い次第終了） ---")
        
        target_set = {str(c).strip()[:4] for c in target_codes}
        needs_bs = set(target_set)
        needs_re = set(target_set)
        
        all_docs = []
        for i in range(days_back + 1):
            if len(needs_bs) == 0 and len(needs_re) == 0:
                print(f"\n★全対象銘柄の必要書類が揃いました！({i}日遡ってスキャン完了)")
                break

            target_date = today - datetime.timedelta(days=i)
            if i % 10 == 0: 
                print(f"  チェック中: {target_date} ... (残り B/S:{len(needs_bs)}社, 不動産:{len(needs_re)}社)", end="")

            url = "https://disclosure.edinet-fsa.go.jp/api/v2/documents.json"
            params = {"date": target_date.strftime('%Y-%m-%d'), "type": 2, "Subscription-Key": EDINET_API_KEY}
            
            try:
                res = requests.get(url, params=params, timeout=10)
                if res.status_code == 200:
                    js = res.json()
                    if "results" in js:
                        count = 0
                        for item in js["results"]:
                            doc_type = item['docTypeCode']
                            sec_code = str(item.get('secCode', ''))[:4]
                            xbrl_flag = item['xbrlFlag']
                            
                            all_docs.append({
                                'date': target_date,
                                'secCode': str(item.get('secCode', '')), 
                                'filerName': item.get('filerName', ''),
                                'docID': item['docID'],
                                'docDescription': item['docDescription'],
                                'docTypeCode': doc_type,
                                'xbrlFlag': xbrl_flag
                            })
                            count += 1
                            
                            if sec_code in target_set:
                                if doc_type in ['120', '130', '140', '150', '160'] and xbrl_flag == '1':
                                    if sec_code in needs_bs: needs_bs.remove(sec_code)
                                if doc_type == '120':
                                    if sec_code in needs_re: needs_re.remove(sec_code)

                        if i % 10 == 0: print(f" -> {count}件")
            except Exception as e: 
                pass
            time.sleep(0.3) 
        
        self.df_docs = pd.DataFrame(all_docs)
        print(f"\n--- 完了: 合計 {len(self.df_docs)} 件の書類情報を確保 ---")

    def find_best_bs_doc(self, code):
        if self.df_docs.empty: return None, "リストが空です", ""
        target_str = str(code).strip()
        search_code = target_str + '0' if len(target_str) == 4 else target_str
        candidates = self.df_docs[self.df_docs['secCode'] == search_code].copy()
        
        if candidates.empty: return None, "コード一致なし", ""
        
        def calculate_score(row):
            score = 0
            dtype = row['docTypeCode']
            if dtype in ['120', '140', '160']: score += 10000
            elif dtype in ['130', '150']: score += 5000
            if row['xbrlFlag'] == '1': score += 1000
            return score

        candidates['score'] = candidates.apply(calculate_score, axis=1)
        candidates = candidates.sort_values(by=['score', 'date', 'docID'], ascending=[False, False, False])
        best = candidates.iloc[0]
        
        if best['score'] < 5000: return None, f"決算書類なし", best['filerName']
        if best['xbrlFlag'] != '1': return None, f"XBRLなし", best['filerName']
        return best['docID'], best['docDescription'], best['filerName']

    def find_best_re_doc(self, code):
        if self.df_docs.empty: return None
        target_str = str(code).strip()
        search_code = target_str + '0' if len(target_str) == 4 else target_str
        candidates = self.df_docs[(self.df_docs['secCode'] == search_code) & (self.df_docs['docTypeCode'] == '120')].copy()
        
        if candidates.empty: return None
        candidates = candidates.sort_values(by='date', ascending=False)
        return candidates.iloc[0]['docID']

# ==========================================
# 3. 解析機能 (B/S)
# ==========================================
TOTAL_TAG_MAP = {
    "Assets": ["Assets", "TotalAssets", "AssetsIFRS", "TotalAssetsIFRSSummaryOfBusinessResults", "TotalAssetsUSGAAPSummaryOfBusinessResults"],
    "CurrentAssets": ["CurrentAssets", "AssetsCurrent", "CurrentAssetsIFRS", "TotalCurrentAssetsIFRS", "CurrentAssetsOtherThanAssetsHeldForSaleCAIFRS"],
    "NonCurrentAssets": ["NoncurrentAssets", "AssetsNoncurrent", "NonCurrentAssetsIFRS", "TotalNonCurrentAssetsIFRS"],
    "Liabilities": ["Liabilities", "TotalLiabilities", "LiabilitiesIFRS", "TotalLiabilitiesIFRSSummaryOfBusinessResults", "TotalLiabilitiesUSGAAPSummaryOfBusinessResults"],
    "CurrentLiabilities": ["CurrentLiabilities", "LiabilitiesCurrent", "CurrentLiabilitiesIFRS", "TotalCurrentLiabilitiesIFRS"],
    "NonCurrentLiabilities": ["NoncurrentLiabilities", "LiabilitiesNoncurrent", "NonCurrentLiabilitiesIFRS", "NonCurrentLabilitiesIFRS", "TotalNonCurrentLiabilitiesIFRS"],
    "NetAssets": [
        "NetAssets", "Equity", "StockholdersEquity", "TotalEquity",
        "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest",
        "EquityAttributableToOwnersOfParent", "EquityIFRS",
        "TotalEquityIFRSSummaryOfBusinessResults",
        "EquityAttributableToOwnersOfParentIFRS",
        "EquityAttributableToOwnersOfParentIFRSSummaryOfBusinessResults",
        "NetAssetsUSGAAPSummaryOfBusinessResults",
        "TotalEquityUSGAAPSummaryOfBusinessResults",
        "StockholdersEquityUSGAAPSummaryOfBusinessResults",
    ],
}
TOTAL_TAG_LOOKUP = {tag: total for total, tags in TOTAL_TAG_MAP.items() for tag in tags}

EXCLUDE_FROM_ITEMS = {
    "EquityAttributableToOwnersOfParentUSGAAPSummaryOfBusinessResults",
    "CashAndCashEquivalentsUSGAAPSummaryOfBusinessResults",
    "AccumulatedOtherComprehensiveIncomeDirectlyRelatedToTheDisposalGroupClassifiedAsHeldForDistributionToOwnersEquityIFRS",
}
INVENTORY_DETAIL_TAGS = {
    "MerchandiseAndFinishedGoods", "WorkInProcess", "RawMaterialsAndSupplies",
    "OtherInventories",
    "MerchandiseAndFinishedGoodsCAIFRS", "FinishedGoodsCAIFRS",
    "SemiFinishedGoodsAndWorkInProcessCAIFRS", "WorkInProcessCAIFRS",
    "RawMaterialsCAIFRS", "RawMaterialsWorkInProgressAndSuppliesCAIFRS",
    "RawMaterialsPurchasedComponentsAndSuppliesCAIFRS",
    "RawMaterialsAndSuppliesCAIFRS",
    "SuppliesAndOtherCAIFRS", "ProductionSuppliesCAIFRS",
    "TelecommunicationsTerminalEquipmentAndMaterialsToBeSoldCAIFRS",
    "RealEstateForSaleCAIFRS",
    "OtherInventoriesCAIFRS",
    "FinishedGoods", "Merchandise", "Supplies", "LandAndBuildingsForSaleInLots",
}
INVENTORY_TOTAL_TAGS = {"Inventories", "InventoriesIFRS", "InventoriesCAIFRS", "InventoryNet"}
PPE_SUMMARY_TAGS = {"PropertyPlantAndEquipmentIFRS"}
PPE_DETAIL_TAGS = {
    "BuildingsAndStructuresIFRS", "MachineryAndEquipmentIFRS", "MachineryAndVehiclesIFRS",
    "MachineryandequipmentIFRS", "MachineryVesselsAndToolsIFRS", "TelecommunicationsEquipmentIFRS",
    "TelecommunicationsServiceLinesIFRS", "MineralResourcesRelatedPropertyIFRS", "LandIFRS",
    "ConstructionInProgressIFRS", "RightOfUseAssetsIFRS", "RightsToUseFacilitiesIFRS",
    "BuildingsAndAccompanyingFacilitiesIFRS", "ToolsFurnitureAndFixturesIFRS",
    "BuildingsNet", "FurnitureAndFixturesNetPPE", "VesselsNet", "AircraftNet", "AircraftAndShipsIFRS", "EquipmentNetPPEWAT",
    "Buildings", "MachineryAndEquipment", "PropertyForLeasePPELEA",
    "AdvancesForPurchasesAtLeasedAssetsPPELEA", "DistributionFacilitiesNCAElectricELE",
    "TransmissionFacilitiesNCAElectricELE", "NuclearPowerProductionFacilitiesNCAElectricELE",
    "HydroelectricPowerProductionFacilitiesNCAElectricELE", "ThermalPowerProductionFacilitiesNCAElectricELE",
    "GeneralFacilitiesNCAElectricELE", "OtherElectricUtilityPlantAndEquipmentNCAElectricELE",
    "TransformationFacilitiesNCAElectricELE", "ConstructionInProgressELE",
    "ConstructionAndRetirementInProgressNCAInProcessELE", "NuclearPowerAbolitionInProgressELE",
}
INTANGIBLE_SUMMARY_TAGS = {"IntangibleAssets", "IntangibleAssetsIFRS", "GoodwillAndIntangibleAssetsIFRS"}
INTANGIBLE_DETAIL_TAGS = {
    "Software", "Goodwill", "LeaseholdRight", "OtherIntangibleAssets", "OtherIA",
    "GoodwillIFRS", "SoftwareIFRS", "SoftwareForInternalUseIFRS", "SoftwareForSaleIFRS",
    "CapitalizedDevelopmentCostsIFRS", "CapitalizedDevelopmentCosts2IFRS",
    "CustomerRelationshipsIFRS", "TechnologiesIFRS",
    "CustomerRelatedAssetsIFRS", "TechnologyBasedIntangibleAssetsIFRS",
    "TrademarksIntangibleAssetsWithIndefiniteUsefulLivesIFRS", "TrademarksIFRS",
    "MusicCatalogsIFRS", "FilmCostIFRS", "ContentAssetsNCAIFRS",
    "BroadcastingRightsIFRS", "GameContentIFRS", "IntangibleAssetsAssociatedWithProductsIFRS",
    "OtherComponentsOfIntangibleAssetsIFRS", "FishFarmingLicenseAndSurfaceRightsIFRS",
    "OtherIntangibleAssetsIFRS", "OtherIntangibleAssetsWithIndefiniteUsefulLivesIFRS",
    "ArtistContractsIFRS", "MusicDistributionRightsIFRS",
    "PatentRightsKnowHowAndLicenseAgreementsIFRS", "TelevisionCarriageContractsIFRS",
}
ADDITIVE_CATS = {
    "流動_棚卸資産", "流動_貸倒引当金", "投資_貸倒引当金",
    "純資_自己株式",
}

NOTE_ONLY_TAG_PATTERNS = [
    "AcquisitionCost",
    "AccumulatedAmortization",
    "AccumulatedDepreciation",
    "AccumulatedImpairment",
    "BookValueEquitySecurities",
    "CarryingAmountShares",
    "NumberOfShares",
    "NumberOfVotingRights",
    "SummaryOfBusinessResults",
    "LiabilitiesAndEquity",
    "LiabilitiesAndNetAssets",
    "InvestmentsAndOtherAssets",
    "PropertyPlantAndEquipment",
    "LiabilitiesOtherThanLiabilitiesDirectlyAssociatedWithAssetsHeldForSale",
    "ShareholdersEquity",
    "RetainedEarningsBroughtForward",
    "OtherRetainedEarnings",
    "LegalCapitalSurplus",
    "GeneralReserve",
    "ForeignCurrencyTranslationAdjustment",
    "ValuationDifferenceOnAvailableForSaleSecurities",
    "DeferredGainsOrLossesOnHedges",
    "BadDebts",
    "OtherEquityInstrumentsEquity",
]

DERIVED_NET_TAG_PAIRS = [
    ("BuildingsAcquisitionCostIFRS", "BuildingsAccumulatedDepreciationAndImpairmentLossesIFRS", "有形_建物・構築物", ["BuildingsIFRS"]),
    ("BuildingsAndStructuresAcquisitionCostIFRS", "BuildingsAndStructuresAccumulatedDepreciationAndImpairmentLossesIFRS", "有形_建物・構築物", ["BuildingsAndStructuresIFRS"]),
    ("MachineryAndEquipmentAcquisitionCostIFRS", "MachineryAndEquipmentAccumulatedDepreciationAndImpairmentLossesIFRS", "有形_機械・運搬具", ["MachineryAndEquipmentIFRS"]),
    ("MachineryandequipmentAcquisitionCostIFRS", "MachineryandequipmentAccumulatedDepreciationAndImpairmentLossesIFRS", "有形_機械・運搬具", ["MachineryandequipmentIFRS"]),
    ("MachineryVesselsAndToolsAcquisitionCostIFRS", "MachineryVesselsAndToolsAccumulatedDepreciationAndImpairmentLossesIFRS", "有形_機械・運搬具", ["MachineryVesselsAndToolsIFRS"]),
    ("TelecommunicationsEquipmentAcquisitionCostIFRS", "TelecommunicationsEquipmentAccumulatedDepreciationAndImpairmentLossesIFRS", "有形_通信設備", ["TelecommunicationsEquipmentIFRS"]),
    ("VehiclesAndEquipmentOnOperatingLeasesAcquisitionCostIFRS", "VehiclesAndEquipmentOnOperatingLeasesAccumulatedDepreciationAndImpairmentIFRS", "有形_賃貸用資産", ["VehiclesAndEquipmentOnOperatingLeasesIFRS"]),
    ("ConstructionInProgressAcquisitionCostIFRS", "ConstructionInProgressAccumulatedImpairmentLossesIFRS", "有形_建設仮勘定", ["ConstructionInProgressIFRS"]),
    ("LandAcquisitionCostIFRS", "LandAccumulatedImpairmentLossesIFRS", "有形_土地", ["LandIFRS"]),
    ("FurnitureAndFixturesAcquisitionCostIFRS", "FurnitureAndFixturesAccumulatedDepreciationAndImpairmentLossesIFRS", "有形_工具器具備品", ["FurnitureAndFixturesIFRS"]),
    ("OtherComponentsOfPropertyPlantAndEquipmentAcquisitionCostIFRS", "OtherComponentsOfPropertyPlantAndEquipmentAccumulatedDepreciationAndImpairmentLossesIFRS", "有形_その他有形固定資産", ["OtherComponentsOfPropertyPlantAndEquipmentIFRS"]),
    ("SoftwareAcquisitionCostIFRS", "SoftwareAccumulatedAmortizationAndImpairmentLossesIFRS", "無形_ソフトウエア", ["SoftwareIFRS"]),
    ("CapitalizedDevelopmentCostsAcquisitionCostIFRS", "CapitalizedDevelopmentCostsAccumulatedAmortizationAndImpairmentLossesIFRS", "無形_その他無形固定資産", ["CapitalizedDevelopmentCostsIFRS"]),
    ("CustomerRelationshipsAcquisitionCostIFRS", "CustomerRelationshipsAccumulatedAmortizationAndImpairmentLossesIFRS", "無形_その他無形固定資産", ["CustomerRelationshipsIFRS"]),
    ("TechnologiesAcquisitionCostIFRS", "TechnologiesAccumulatedAmortizationAndImpairmentLossesIFRS", "無形_その他無形固定資産", ["TechnologiesIFRS"]),
    ("SpectrumMigrationCostsAcquisitionCostIFRS", "SpectrumMigrationCostsAccumulatedAmortizationAndImpairmentLossesIFRS", "無形_その他無形固定資産", ["SpectrumMigrationCostsIFRS"]),
    ("OtherIntangibleAssetsWithFiniteUsefulLivesAcquisitionCostIFRS", "OtherIntangibleAssetsWithFiniteUsefulLivesAccumulatedAmortizationAndImpairmentLossesIFRS", "無形_その他無形固定資産", ["OtherIntangibleAssetsWithFiniteUsefulLivesIFRS"]),
    ("OtherComponentsOfIntangibleAssetsAcquisitionCostIFRS", "OtherComponentsOfIntangibleAssetsAccumulatedAmortizationAndImpairmentLossesIFRS", "無形_その他無形固定資産", ["OtherComponentsOfIntangibleAssetsIFRS"]),
]

def get_tag_name(el):
    return el.name.split(':')[-1]

def parse_xbrl_number(text):
    text_str = text.strip()
    if not re.match(r'^-?[\d\.]+$', text_str):
        return None
    try:
        return int(float(text_str))
    except Exception:
        return None

def get_context_score(cid, ctx):
    score = 0
    cid_text = cid or ""
    members = [m.text for m in ctx.find_all(re.compile(r'.*explicitMember'))]
    if "CurrentYear" in cid_text or "Current" in cid_text:
        score += 200
    if "Prior" in cid_text:
        score -= 500
    if "NonConsolidated" in cid_text:
        score -= 120
    if "Consolidated" in cid_text and "NonConsolidated" not in cid_text:
        score += 120
    if any("NonConsolidatedMember" in m for m in members):
        score -= 120
    if any("ConsolidatedMember" in m for m in members):
        score += 120
    if any("Axis" in m or "Member" in m for m in members):
        score -= 20 * len(members)
    return score

def is_main_bs_context(ctx, end_date):
    cid = ctx.get('id')
    instant = ctx.find(re.compile(r'.*instant'))
    if not cid or not instant:
        return False
    if end_date and instant.text.strip() != end_date:
        return False

    members = ctx.find_all(re.compile(r'.*explicitMember'))
    for member in members:
        text = member.text
        if "ConsolidatedMember" not in text and "NonConsolidatedMember" not in text:
            return False
    return True

def should_skip_item_tag(tag, raw_tags):
    if tag in EXCLUDE_FROM_ITEMS:
        return "excluded_summary_or_special_tag"
    if tag in INVENTORY_DETAIL_TAGS and any(k in raw_tags for k in INVENTORY_TOTAL_TAGS):
        return "inventory_detail_skipped_because_total_exists"
    if tag == "InventoriesCAIFRS" and "InventoriesIFRS" in raw_tags:
        return "duplicate_ifrs_inventory_total"
    if tag == "EquityIFRS" and any(k in raw_tags for k in ["ShareCapitalIFRS", "RetainedEarningsIFRS"]):
        return "equity_summary_skipped_because_details_exist"
    if tag in PPE_SUMMARY_TAGS and any(k in raw_tags for k in PPE_DETAIL_TAGS):
        return "ppe_summary_skipped_because_details_exist"
    if tag in INTANGIBLE_SUMMARY_TAGS and any(k in raw_tags for k in INTANGIBLE_DETAIL_TAGS):
        return "intangible_summary_skipped_because_details_exist"
    if tag == "LeaseAssetsPPE" and "LeaseAssetsNetPPE" in raw_tags:
        return "gross_lease_assets_skipped_because_net_exists"
    if tag == "OtherPPE" and "OtherNetPPE" in raw_tags:
        return "gross_other_ppe_skipped_because_net_exists"
    if not tag.endswith("Net") and (tag + "Net") in raw_tags:
        return "gross_value_skipped_because_net_exists"
    return None

def apply_mapped_tag(summary, tag, val):
    cat = TAG_MAPPING[tag]
    if cat not in summary:
        summary[cat] = 0
    if cat in ADDITIVE_CATS:
        summary[cat] += val
        return "add"
    previous = summary[cat]
    summary[cat] = max(previous, val)
    return "max"

def apply_derived_net_tag_pairs(summary, raw_tags, applied_tags):
    for gross_tag, accumulated_tag, category, base_tags in DERIVED_NET_TAG_PAIRS:
        if gross_tag not in raw_tags or accumulated_tag not in raw_tags:
            continue
        if any(base_tag in raw_tags and base_tag in TAG_MAPPING for base_tag in base_tags):
            continue

        net_value = raw_tags[gross_tag] + raw_tags[accumulated_tag]
        if net_value <= 0:
            continue

        if category not in summary:
            summary[category] = 0
        summary[category] += net_value
        applied_tags.append({
            "tag": f"{gross_tag}+{accumulated_tag}",
            "category": category,
            "value": net_value,
            "action": "derived_net_add",
        })

OTHER_CATEGORIES = [
    "流動_その他流動資産",
    "投資_その他固定資産",
    "流負_その他流動負債",
    "固負_その他固定負債",
    "純資_その他純資産",
]

def build_bs_warnings(summary, totals, gap_diagnostics=None, reported_other_values=None):
    warnings_list = []

    def add_total_warning(label, total, subtotal):
        if not total or not subtotal:
            return
        diff = total - subtotal
        threshold = max(abs(total) * 0.01, 1_000_000_000)
        if abs(diff) > threshold:
            warnings_list.append(f"{label}: 合計整合性に差があります ({diff / 1e8:,.1f}億円)")

    add_total_warning(
        "資産合計 vs 流動資産+固定資産",
        totals.get("Assets", 0),
        totals.get("CurrentAssets", 0) + totals.get("NonCurrentAssets", 0),
    )
    add_total_warning(
        "負債合計 vs 流動負債+固定負債",
        totals.get("Liabilities", 0),
        totals.get("CurrentLiabilities", 0) + totals.get("NonCurrentLiabilities", 0),
    )
    add_total_warning(
        "資産合計 vs 負債合計+純資産合計",
        totals.get("Assets", 0),
        totals.get("Liabilities", 0) + totals.get("NetAssets", 0),
    )

    if gap_diagnostics:
        for key, info in gap_diagnostics.items():
            total = info.get("total", 0)
            gap = info.get("gap", 0)
            reported = (reported_other_values or {}).get(key)
            threshold = max(abs(total) * 0.03, 1_000_000_000)
            if reported not in (None, 0):
                delta = info.get("delta_from_reported", gap - reported)
                if total and abs(delta) > threshold:
                    warnings_list.append(f"{key}: 内訳の未分類差額が大きいです ({delta / 1e8:,.1f}億円)")
            elif total and abs(gap) > threshold:
                warnings_list.append(f"{key}: 合計との差額補完が大きいです ({gap / 1e8:,.1f}億円)")

    for key in OTHER_CATEGORIES:
        val = summary.get(key, 0)
        basis = totals.get("Assets", 0) or 1
        if val < 0 and abs(val) > abs(basis) * 0.03:
            warnings_list.append(f"{key}: その他項目が大きなマイナスです ({val / 1e8:,.1f}億円)")

    return warnings_list

def analyze_bs_xbrl(doc_id, debug=False):
    url = f"https://disclosure.edinet-fsa.go.jp/api/v2/documents/{doc_id}"
    params = {"type": 1, "Subscription-Key": EDINET_API_KEY}
    try: 
        res = requests.get(url, params=params, timeout=10)
        if res.status_code != 200: return None
        z_data = io.BytesIO(res.content)
    except: return None
    
    summary = {k: 0 for k in DISPLAY_ORDER}
    totals = {"Assets":0, "CurrentAssets":0, "NonCurrentAssets":0, "Liabilities":0, "CurrentLiabilities":0, "NonCurrentLiabilities":0, "NetAssets":0}

    with zipfile.ZipFile(z_data) as z:
        xbrl_file = next((n for n in z.namelist() if n.endswith(".xbrl") and "PublicDoc" in n), None)
        if not xbrl_file: return None
        
        with z.open(xbrl_file) as f:
            try: soup = BeautifulSoup(f, 'lxml-xml')
            except: soup = BeautifulSoup(f, 'html.parser')

            doc_type = "J-GAAP"
            # Fast check using raw string
            f.seek(0)
            raw_text = f.read().decode('utf-8').lower()
            if 'ifrs-full:' in raw_text or 'ifrs:' in raw_text or 'jpigp_cor:' in raw_text: doc_type = "IFRS"
            elif 'us-gaap:' in raw_text: doc_type = "US GAAP"
            
            dei = soup.find(re.compile(r'.*CurrentPeriodEndDate'))
            end_date = dei.text.strip() if dei else None
            
            valid_contexts = []
            for ctx in soup.find_all(re.compile(r'.*context')):
                cid = ctx.get('id')
                if is_main_bs_context(ctx, end_date):
                    valid_contexts.append({
                        "id": cid,
                        "score": get_context_score(cid, ctx),
                        "members": [m.text for m in ctx.find_all(re.compile(r'.*explicitMember'))],
                    })
            
            # 各候補で実際に何個タグが取れるか試してみて、最もヒット数が多いものを採用する
            # ※高速化のため、すべての要素を一度だけ探索して contextRef ごとにまとめる
            elements_by_ctx = {}
            for el in soup.find_all():
                ctx_ref = el.get('contextRef')
                if ctx_ref:
                    elements_by_ctx.setdefault(ctx_ref, []).append(el)

            best_rank = (-1, -1)
            best_res = (summary, totals, {}, {})
            best_cid = None
            debug_contexts = []
            
            for ctx_info in valid_contexts:
                cid = ctx_info["id"]
                temp_summary = {k: 0 for k in DISPLAY_ORDER}
                temp_totals = {k: 0 for k in totals}
                hits = 0
                
                raw_tags = {}
                raw_tag_candidates = {}
                applied_tags = []
                skipped_tags = []
                elements = elements_by_ctx.get(cid, [])
                for el in elements:
                    val = parse_xbrl_number(el.text)
                    if val is None:
                        continue
                    tag = get_tag_name(el)
                    raw_tag_candidates.setdefault(tag, []).append({
                        "value": val,
                        "unitRef": el.get("unitRef"),
                        "decimals": el.get("decimals"),
                    })
                    raw_tags[tag] = val
                    
                    total_key = TOTAL_TAG_LOOKUP.get(tag)
                    if total_key:
                        temp_totals[total_key] = max(temp_totals[total_key], val)
                
                for tag, val in raw_tags.items():
                    if tag in TAG_MAPPING:
                        skip_reason = should_skip_item_tag(tag, raw_tags)
                        if skip_reason:
                            skipped_tags.append({"tag": tag, "value": val, "reason": skip_reason})
                            continue
                        action = apply_mapped_tag(temp_summary, tag, val)
                        applied_tags.append({"tag": tag, "category": TAG_MAPPING[tag], "value": val, "action": action})
                            
                        hits += 1

                apply_derived_net_tag_pairs(temp_summary, raw_tags, applied_tags)
                
                total_completeness = sum(1 for v in temp_totals.values() if v != 0)
                rank = (ctx_info["score"] + total_completeness * 80, hits)
                debug_contexts.append({
                    "id": cid,
                    "context_score": ctx_info["score"],
                    "rank": rank,
                    "hits": hits,
                    "total_completeness": total_completeness,
                    "members": ctx_info["members"],
                    "totals": temp_totals,
                    "duplicate_tags": {k: v for k, v in raw_tag_candidates.items() if len(v) > 1},
                    "applied_tags": applied_tags if debug else [],
                    "skipped_tags": skipped_tags if debug else [],
                })
                
                if rank > best_rank:
                    best_rank = rank
                    best_cid = cid
                    best_res = (temp_summary, temp_totals, raw_tags, raw_tag_candidates)
            
            summary, totals, best_raw_tags, best_raw_tag_candidates = best_res
            diagnostics = {
                "doc_id": doc_id,
                "doc_type": doc_type,
                "end_date": end_date,
                "selected_context": best_cid,
                "selected_rank": best_rank,
                "contexts": debug_contexts,
                "duplicate_tags_in_selected_context": {k: v for k, v in best_raw_tag_candidates.items() if len(v) > 1},
            }

    if summary["流動_受取手形"] > 0 or summary["流動_売掛金"] > 0:
        summary["流動_受取手形・売掛金(合算)"] = 0

    if totals["NonCurrentAssets"] == 0 and totals["Assets"] != 0:
        totals["NonCurrentAssets"] = totals["Assets"] - totals["CurrentAssets"]
    if totals["NonCurrentLiabilities"] == 0 and totals["Liabilities"] != 0:
        totals["NonCurrentLiabilities"] = totals["Liabilities"] - totals["CurrentLiabilities"]

    reported_other_values = {key: summary.get(key, 0) for key in OTHER_CATEGORIES}
    gap_diagnostics = {}

    def calc_gap(p, t, o):
        # Totals=0ならサマリに詳細タグが取れているとしても差引計算をしない(歪みを防ぐ)
        if totals[t] == 0:
            summary[o] = 0
            gap_diagnostics[o] = {"total_key": t, "total": 0, "subtotal": 0, "gap": 0, "reason": "total_missing"}
            return
        s = sum(summary[k] for k in summary if k.startswith(p) and k != o)
        gap = totals[t] - s
        reported = reported_other_values.get(o, 0)
        if reported != 0:
            summary[o] = reported
            source = "reported_other_tag"
        else:
            summary[o] = gap
            source = "computed_gap"
        gap_diagnostics[o] = {
            "total_key": t,
            "total": totals[t],
            "subtotal": s,
            "gap": gap,
            "reported": reported,
            "selected": summary[o],
            "selected_source": source,
            "delta_from_reported": gap - reported if reported != 0 else gap,
        }
    
    calc_gap("流動_", "CurrentAssets", "流動_その他流動資産")
    # 非流動資産の「その他」も同様
    if totals["NonCurrentAssets"] != 0:
        sum_fixed = sum(summary[k] for k in summary if (k.startswith("有形_") or k.startswith("無形_") or k.startswith("投資_")) and k != "投資_その他固定資産")
        gap = totals["NonCurrentAssets"] - sum_fixed
        reported = reported_other_values.get("投資_その他固定資産", 0)
        if reported != 0:
            summary["投資_その他固定資産"] = reported
            source = "reported_other_tag"
        else:
            summary["投資_その他固定資産"] = gap
            source = "computed_gap"
        gap_diagnostics["投資_その他固定資産"] = {
            "total_key": "NonCurrentAssets",
            "total": totals["NonCurrentAssets"],
            "subtotal": sum_fixed,
            "gap": gap,
            "reported": reported,
            "selected": summary["投資_その他固定資産"],
            "selected_source": source,
            "delta_from_reported": gap - reported if reported != 0 else gap,
        }
    calc_gap("流負_", "CurrentLiabilities", "流負_その他流動負債")
    calc_gap("固負_", "NonCurrentLiabilities", "固負_その他固定負債")
    if totals["NetAssets"] != 0:
        sum_net = sum(summary[k] for k in summary if k.startswith("純資_") and k != "純資_その他純資産")
        gap = totals["NetAssets"] - sum_net
        reported = reported_other_values.get("純資_その他純資産", 0)
        if reported != 0:
            summary["純資_その他純資産"] = reported
            source = "reported_other_tag"
        else:
            summary["純資_その他純資産"] = gap
            source = "computed_gap"
        gap_diagnostics["純資_その他純資産"] = {
            "total_key": "NetAssets",
            "total": totals["NetAssets"],
            "subtotal": sum_net,
            "gap": gap,
            "reported": reported,
            "selected": summary["純資_その他純資産"],
            "selected_source": source,
            "delta_from_reported": gap - reported if reported != 0 else gap,
        }
    else:
        summary["純資_その他純資産"] = 0
        gap_diagnostics["純資_その他純資産"] = {"total_key": "NetAssets", "total": 0, "subtotal": 0, "gap": 0, "reason": "total_missing"}

    bs_warnings = build_bs_warnings(summary, totals, gap_diagnostics, reported_other_values)
    if debug:
        known_numeric_tags = set(TAG_MAPPING) | set(TOTAL_TAG_LOOKUP)
        unmapped_numeric_tags = [
            {"tag": tag, "value_oku": round(val / 100000000, 3)}
            for tag, val in sorted(best_raw_tags.items(), key=lambda item: abs(item[1]), reverse=True)
            if tag not in known_numeric_tags and abs(val) >= 100000000
        ]
        note_only_unmapped_tags = [
            item for item in unmapped_numeric_tags
            if any(pattern in item["tag"] for pattern in NOTE_ONLY_TAG_PATTERNS)
        ]
        mapping_candidate_unmapped_tags = [
            item for item in unmapped_numeric_tags
            if item not in note_only_unmapped_tags
        ]
        diagnostics["gap_diagnostics"] = gap_diagnostics
        diagnostics["warnings"] = bs_warnings
        diagnostics["reported_other_values_oku"] = {
            k: round(v / 100000000, 3) for k, v in reported_other_values.items() if v != 0
        }
        diagnostics["other_gap_delta_oku"] = {
            k: round(info.get("delta_from_reported", 0) / 100000000, 3)
            for k in OTHER_CATEGORIES
            for info in [gap_diagnostics.get(k, {})]
            if info.get("delta_from_reported", 0) != 0
        }
        diagnostics["unmapped_numeric_tags_over_1oku"] = unmapped_numeric_tags[:100]
        diagnostics["note_only_unmapped_tags_over_1oku"] = note_only_unmapped_tags[:100]
        diagnostics["mapping_candidate_unmapped_tags_over_1oku"] = mapping_candidate_unmapped_tags[:100]
        diagnostics["summary_nonzero_oku"] = {k: round(v / 100000000, 3) for k, v in summary.items() if v != 0}
        diagnostics["totals_oku"] = {k: round(v / 100000000, 3) for k, v in totals.items()}
        return summary, totals, doc_type, best_raw_tags, diagnostics
    
    return summary, totals, doc_type, best_raw_tags


# --- 解析用ヘルパー関数群 ---
def normalize_str(obj):
    if obj is None: return ""
    return unicodedata.normalize('NFKC', str(obj)).replace(' ', '').replace('\n', '').replace('\u3000', '')

def get_valid_number(text):
    if pd.isna(text) or text is None: return None
    text_str = str(text)
    
    # 改行や空白で区切ってブロックごとに評価 (1869のようなHTML重複対策)
    blocks = re.split(r'[\n\s\u3000]+', text_str.strip())
    
    for block in blocks:
        normalized = unicodedata.normalize('NFKC', block).replace('△', '-').replace('▲', '-')
        normalized = re.sub(r'※\d+', '', normalized)
        normalized = re.sub(r'\(注\d*\)', '', normalized)
        
        clean_text = re.sub(r'[^\d\.\-]', '', normalized)
        try:
            if clean_text and re.fullmatch(r'-?\d+(\.\d+)?', clean_text):
                val = float(clean_text)
                if abs(val) < 10 and val.is_integer(): continue
                return val
        except: pass

    return None

def detect_unit(text):
    text = normalize_str(text)
    if "単位:百万円" in text or "単位：百万円" in text or "(百万円)" in text or "（百万円）" in text: return 1000000
    if "単位:千円" in text or "単位：千円" in text or "(千円)" in text or "（千円）" in text: return 1000
    if "単位:円" in text or "単位：円" in text: return 1
    return 1000000 

def resolve_sum_or_max(values):
    if not values: return 0
    if len(values) == 1: return values[0]
    total_sum = sum(values)
    max_val = max(values)
    rest_sum = total_sum - max_val
    if rest_sum > 0 and abs(max_val - rest_sum) / max_val < 0.05: return max_val
    return total_sum

def analyze_single_table(tbl_soup, prev_text):
    unit = detect_unit(tbl_soup.get_text())
    if unit == 1000000: unit = detect_unit(prev_text)

    try:
        dfs = pd.read_html(io.StringIO(str(tbl_soup)), header=None)
        if not dfs: return 0, 0
        df = dfs[0]
    except: return 0, 0

    rows, cols = df.shape
    if rows < 2 or cols < 2: return 0, 0

    target_col_indices = []
    col_headers = ["".join([normalize_str(df.iloc[r, c]) for r in range(min(5, rows))]) for c in range(cols)]

    for c in range(cols):
        h_text = col_headers[c]
        if "当" in h_text and any(x in h_text for x in ["連結", "事業", "年度", "期"]):
            if "前期" not in h_text and "期首" not in h_text:
                target_col_indices.append(c)
    
    if not target_col_indices:
        for c in range(cols - 1, 0, -1):
            if any(x in col_headers[c] for x in ["前連結", "前事業", "前期", "増減"]): continue
            for r in range(rows):
                if get_valid_number(df.iloc[r, c]) is not None:
                    target_col_indices.append(c)
                    break 
            if target_col_indices: break

    if not target_col_indices: return 0, 0
    target_col = target_col_indices[-1]

    found_books, found_markets = [], []
    for r in range(rows):
        row_label = "".join([normalize_str(df.iloc[r, c]) for c in range(target_col)])
        val = get_valid_number(df.iloc[r, target_col])
        if val is None: continue

        is_book_row = False
        if "期末" in row_label and ("残高" in row_label or "計上額" in row_label): is_book_row = True
        elif "貸借対照表計上額" in row_label or "帳簿価額" in row_label: is_book_row = True

        if is_book_row and any(x in row_label for x in ["期首", "増減", "償却", "損益"]): is_book_row = False
        if is_book_row and "期首" not in row_label: found_books.append(val)
        if "時価" in row_label: found_markets.append(val)

    return resolve_sum_or_max(found_books) * unit, resolve_sum_or_max(found_markets) * unit

# ★【追加】有価証券の「取得原価を超えるもの」の差額を取得する関数
def analyze_securities_table(tbl_soup, prev_text):
    unit = detect_unit(tbl_soup.get_text())
    if unit == 1000000: unit = detect_unit(prev_text)

    try:
        dfs = pd.read_html(io.StringIO(str(tbl_soup)), header=None)
        if not dfs: return 0
        df = dfs[0]
    except: return 0

    rows, cols = df.shape
    if rows < 2 or cols < 2: return 0

    is_valid_table = False
    diff_col_idx = -1
    for r in range(rows):
        row_values = []
        for c in range(cols):
            v = get_valid_number(df.iloc[r, c])
            if v is not None: row_values.append((c, v))
        
        # 3つの値 A, B, C があり、 A - B = C が成り立つ組み合わせを探す
        for i in range(len(row_values)):
            for j in range(len(row_values)):
                for k in range(len(row_values)):
                    if i == j or j == k or i == k: continue
                    ci, vi = row_values[i]; cj, vj = row_values[j]; ck, vk = row_values[k]
                    if vk > 0 and abs(vi - vj - vk) < 5:
                        is_valid_table = True
                        diff_col_idx = ck
                        break
                if is_valid_table: break
            if is_valid_table: break
        if is_valid_table: break
    
    if not is_valid_table:
        diff_col_idx = -1
        for c in range(cols):
            col_text = "".join([normalize_str(df.iloc[r, c]) for r in range(min(5, rows))])
            if any(x in col_text for x in ["差額", "評価差額", "評価益", "含み損益", "z"]): 
                diff_col_idx = c
                break
        if diff_col_idx == -1:
            for c in range(cols):
                for r in range(min(10, rows)):
                    norm_val = normalize_str(df.iloc[r, c])
                    if any(x in norm_val for x in ["差額", "評価差額", "評価益", "含み損益", "z"]):
                        diff_col_idx = c
                        break
                if diff_col_idx != -1: break
    
    if diff_col_idx == -1: return 0
    if not is_valid_table and diff_col_idx <= 1: return 0

    found_values = []
    in_exceed_section = False

    for r in range(rows):
        row_label = "".join([normalize_str(df.iloc[r, c]) for c in range(diff_col_idx)])

        # 1行目はラベルにかかわらず「超えるもの」である可能性が高い（特に mojibake 時）
        is_matched = any(x in row_label for x in ["超える", "超過", "プラス"])
        if is_matched:
            in_exceed_section = True
        elif any(x in row_label for x in ["超えない", "以下", "合計", "マイナス"]):
            in_exceed_section = False  
        elif r == 0 and len(found_values) == 0: 
            # バックアップ：最初の数行でまだ何も見つかっていなければ、暫定的に True にしてみる
            in_exceed_section = True

        if in_exceed_section:
            val = get_valid_number(df.iloc[r, diff_col_idx])
            if val is not None and val > 0:
                found_values.append(val)
                # 一度値が見つかったら、次の行が合計や「超えない」なら in_exceed_section を False にする
                # ただし、3202のように1行しかない場合はそのまま終わる
    
    # 合計値が混ざっているのを防ぐため、resolve_sum_or_max で調整
    return resolve_sum_or_max(found_values) * unit

# ★ 不動産と有価証券を両方取得するように拡張
def analyze_real_estate_and_securities_html(doc_id):
    url = f"https://disclosure.edinet-fsa.go.jp/api/v2/documents/{doc_id}"
    params = {"type": 1, "Subscription-Key": EDINET_API_KEY}
    final_res = {"Book": 0, "Market": 0, "Sec_Profit": 0}

    z_data = None
    for _ in range(3):
        try: 
            res = requests.get(url, params=params, timeout=10)
            if res.status_code == 200:
                z_data = io.BytesIO(res.content)
                break
        except: pass
        time.sleep(1)
        
    if not z_data: return final_res
    
    try:
        with zipfile.ZipFile(z_data) as z:
            html_files = [n for n in z.namelist() if n.endswith(".htm") and "PublicDoc" in n]
            for h_file in html_files:
                with z.open(h_file) as f:
                    content = f.read()
                    try:
                        content_str = content.decode('utf-8-sig')
                    except:
                        content_str = content.decode('cp932', errors='replace')
                    
                    # === 高速化: 不要なHTMLをスキップ（精度を落とさないようタグ除去して判定） ===
                    quick_text = re.sub(r'<[^>]+>', '', content_str).replace(' ', '').replace('\n', '').replace('\u3000', '')
                    if not any(x in quick_text for x in ["不動産", "期末時価", "取得", "評価差", "評価益", "含み損益", "v", "z", "擾"]):
                        continue
                        
                    soup = BeautifulSoup(content_str, 'lxml')
                    for tbl in soup.find_all('table'):
                        tbl_text = normalize_str(tbl.get_text())
                        prev_text, curr = "", tbl
                        for _ in range(15):
                            curr = curr.previous_element
                            if not curr: break
                            if getattr(curr, 'name', '') in ['h3', 'h4', 'h5', 'p', 'div']:
                                t = normalize_str(curr.get_text())
                                if len(t) > 2: prev_text = t + " " + prev_text
                        
                        # 不動産の解析
                        is_re_target = False
                        if "賃貸等不動産" in prev_text or "投資不動産" in prev_text: is_re_target = True
                        if "賃貸等不動産" in tbl_text or "投資不動産" in tbl_text: is_re_target = True
                        if "期末時価" in tbl_text: is_re_target = True

                        if is_re_target:
                            b, m = analyze_single_table(tbl, prev_text)
                            if m > final_res["Market"]:
                                final_res["Market"], final_res["Book"] = m, b
                            elif m == final_res["Market"] and m > 0 and b > final_res["Book"]:
                                final_res["Book"] = b

                        # 有価証券の解析
                        is_sec_target = False
                        if "前連結" in prev_text or "前事業" in prev_text or "前期" in prev_text: pass
                        elif "株主資本" in prev_text or "自己株式" in prev_text: pass
                        else:
                            has_acq = any(x in tbl_text for x in ["取得原価", "取得価額", "取得", "擾"])
                            has_diff = any(x in tbl_text for x in ["差額", "評価差額", "評価益", "含み損益", "z"])
                            has_bs = any(x in tbl_text for x in ["貸借対照表", "計上額", "貸借対照表計上額", "v"])
                            
                            if ("有価証券" in prev_text or "有価証券" in tbl_text) and (has_acq or has_diff):
                                is_sec_target = True
                            elif has_acq and has_diff and (has_bs or "v" in tbl_text):
                                is_sec_target = True
                            elif has_acq and has_diff:
                                is_sec_target = True
                            
                        if is_sec_target:
                            sec_profit = analyze_securities_table(tbl, prev_text)
                            if sec_profit > 0:
                                final_res["Sec_Profit"] = sec_profit
    except: pass

    b_oku = round(final_res["Book"] / 100000000, 2)
    m_oku = round(final_res["Market"] / 100000000, 2)
    sec_oku = round(final_res["Sec_Profit"] / 100000000, 2)
    return {
        "不動産_簿価_億": b_oku,
        "不動産_時価_億": m_oku,
        "不動産_含み益_億": round(m_oku - b_oku, 2) if m_oku > 0 else 0,
        "有価証券_含み益_億": sec_oku
    }

# ==========================================
# 4. Yahoo Finance データ取得 
# ==========================================
def get_valid_ticker_and_price(code):
    suffixes = ['.T', '.S', '.F', '.N'] 
    for suffix in suffixes:
        symbol = f"{code}{suffix}"
        try:
            ticker = yf.Ticker(symbol)
            try:
                info = ticker.info
                if info and info.get('currentPrice'):
                    return ticker, info['currentPrice']
            except: pass
            hist = ticker.history(period="1d")
            if not hist.empty:
                return ticker, hist['Close'].iloc[-1]
        except: continue
    return None, 0

def scrape_fallback_data(code):
    import re, requests
    from bs4 import BeautifulSoup
    headers = {'User-Agent': 'Mozilla/5.0'}
    
    data = {
        "price": 0, "mcap_oku": 0, "div_yield": 0, "per": 0,
        "pbr": 0, "eps": 0, "roe": 0, "bps": 0
    }
    
    # 1. Minkabu (株価・時価総額)
    try:
        url_mk = f"https://minkabu.jp/stock/{code}"
        res_mk = requests.get(url_mk, headers=headers, timeout=5)
        if res_mk.status_code == 200:
            soup_mk = BeautifulSoup(res_mk.text, 'html.parser')
            pr_elem = soup_mk.find('div', class_='stock_price')
            if pr_elem:
                p_str = re.sub(r'[^\d.]', '', pr_elem.text.strip())
                if p_str: data["price"] = float(p_str)
            mcap_th = soup_mk.find(string=re.compile("時価総額"))
            if mcap_th:
                mcap_td = mcap_th.find_next('td')
                if mcap_td:
                    m_str = re.sub(r'[^\d.]', '', mcap_td.text)
                    if m_str: data["mcap_oku"] = float(m_str) / 100
    except: pass

    # 2. Yahoo Finance Japan (各種指標)
    def extract_num(text, keyword):
        if keyword not in text: return 0
        idx = text.find(keyword) + len(keyword)
        sub = text[idx:].replace('(連)', '').replace('(単)', '').replace(' ', '')
        m = re.search(r'[\d,]+\.?\d*', sub)
        if m:
            try: return float(m.group(0).replace(',', ''))
            except: return 0
        return 0

    try:
        suffixes = ['.N', '.S', '.F']
        soup_yj = None
        for suf in suffixes:
            url_yj = f"https://finance.yahoo.co.jp/quote/{code}{suf}"
            res_yj = requests.get(url_yj, headers=headers, timeout=5)
            # Yahoo Japan Financeは銘柄がなくても200を返し、「一致する銘柄は見つかりませんでした」等になる場合がある
            soup_temp = BeautifulSoup(res_yj.text, 'html.parser')
            if soup_temp.find(string=re.compile("時価総額")):
                soup_yj = soup_temp
                break
        
        if soup_yj:
            for li in soup_yj.find_all('li'):
                t = li.text.strip().replace('\n', '')
                if '配当利回り' in t and data['div_yield'] == 0: data['div_yield'] = extract_num(t, '配当利回り')
                elif 'PER' in t and ('会社予想' in t or '予想' in t) and data['per'] == 0: data['per'] = extract_num(t, 'PER')
                elif 'PBR' in t and data['pbr'] == 0: data['pbr'] = extract_num(t, 'PBR')
                elif 'EPS' in t and data['eps'] == 0: data['eps'] = extract_num(t, 'EPS')
                elif 'BPS' in t and data['bps'] == 0: data['bps'] = extract_num(t, 'BPS')
                elif 'ROE' in t and data['roe'] == 0: data['roe'] = extract_num(t, 'ROE')
    except: pass

    return data

def get_financial_data(code):
    ticker, price = get_valid_ticker_and_price(code)
    fb = {}
    if not ticker or price == 0:
        # 名証などYahooで取得できない銘柄はみんかぶ・Yahooファイナンスからスクレイピング
        fb = scrape_fallback_data(code)
        price = fb.get("price", 0)
        
    data = {
        "株価": price,
        "配当利回り_pct": 0, "EPS": 0, "PBR": 0, "PER": 0, "ROE_pct": 0,
        "4年平均PER_赤字除": 0, "時価総額_億": fb.get("mcap_oku", 0), "4年赤字率_pct": 0, 
        "4年自社株買い利回り_pct": 0, "4年平均自社株買い_億": 0, "4年平均総還元額_億": 0,
        "10年平均時価総額_億": 0, "4年平均還元利回り_pct": 0, "4年自社株買い比率_pct": 0,
        "4年最低営業利益_億": 0, "4年最低経常利益_億": 0, "純資産_億": 0,
        "10年増配率_pct": 0, "10年減配率_pct": 0, "配当性向_pct": 0
    }
    
    if not ticker:
        # フォールバック時: 独自に取得した指標をセット
        data["配当利回り_pct"] = fb.get("div_yield", 0)
        data["EPS"] = fb.get("eps", 0)
        data["PBR"] = fb.get("pbr", 0)
        data["PER"] = fb.get("per", 0)
        data["ROE_pct"] = fb.get("roe", 0)
        
        # 純資産(億)の計算: みんかぶの時価総額 / PBR (※PBRが取得できている場合)
        if data["PBR"] > 0 and data["時価総額_億"] > 0:
            data["純資産_億"] = round(data["時価総額_億"] / data["PBR"], 1)
        elif fb.get("bps", 0) > 0 and fb.get("price", 0) > 0 and data["時価総額_億"] > 0:
            # 株式数 = 時価総額 / 株価
            shares = (data["時価総額_億"] * 100000000) / fb.get("price")
            data["純資産_億"] = round((fb.get("bps") * shares) / 100000000, 1)

        # 配当性向の計算: 1株配当 / EPS
        if data["EPS"] > 0 and data["配当利回り_pct"] > 0 and fb.get("price", 0) > 0:
            div_per_share = fb.get("price") * (data["配当利回り_pct"] / 100)
            data["配当性向_pct"] = round((div_per_share / data["EPS"]) * 100, 1)

        return data 
    try: info = ticker.info
    except: info = {}

    if data["株価"] == 0: data["株価"] = info.get('currentPrice', 0)
    shares = info.get('sharesOutstanding', 0)
    market_cap_oku = info.get('marketCap', 0)
    if market_cap_oku == 0 and shares > 0 and data["株価"] > 0:
        market_cap_oku = data["株価"] * shares
    data["時価総額_億"] = round(market_cap_oku / 100000000, 1)
    
    div_rate = info.get('dividendRate', 0)
    div_yield = (div_rate / data["株価"] * 100) if data["株価"] > 0 else 0
    if div_yield == 0: div_yield = info.get('dividendYield', 0) * 100
    if div_yield: data["配当利回り_pct"] = round(div_yield, 2)

    if info.get('trailingEps'): data["EPS"] = round(info.get('trailingEps'), 2)
    if info.get('priceToBook'): data["PBR"] = round(info.get('priceToBook'), 2)
    if info.get('trailingPE'): data["PER"] = round(info.get('trailingPE'), 2)
    payout = info.get('payoutRatio', 0)
    data["配当性向_pct"] = round(payout * 100, 1) if payout else 0
    roe = info.get('returnOnEquity', 0)
    if roe: data["ROE_pct"] = round(roe * 100, 2)
    if data["PBR"] > 0: data["純資産_億"] = round(data["時価総額_億"] / data["PBR"], 1)

    try:
        hist_10y = ticker.history(period="10y")
        if not hist_10y.empty and shares > 0:
            data["10年平均時価総額_億"] = round((hist_10y['Close'].mean() * shares) / 100000000, 1)
        divs = ticker.dividends
        if not divs.empty:
            divs.index = divs.index.tz_localize(None)
            yearly = divs.resample('YE').sum().tail(11)
            if len(yearly) > 1:
                pct = yearly.pct_change().dropna()
                data["10年増配率_pct"] = round((pct > 0).sum() / len(pct) * 100, 1)
                data["10年減配率_pct"] = round((pct < 0).sum() / len(pct) * 100, 1)
                
        financials = ticker.financials
        cashflow = ticker.cashflow
        if not financials.empty:
            cols = financials.columns[:4] 
            years_count = len(cols)
            
            avg_mc_4y = data["時価総額_億"]
            hist_4y = hist_10y.tail(int(365 * 4 * 0.7)) if not hist_10y.empty else pd.DataFrame()
            if not hist_4y.empty and shares > 0:
                avg_mc_4y = float((hist_4y['Close'].mean() * shares) / 100000000)

            op_incomes, ord_incomes, net_incomes, buybacks, total_returns, per_history = [], [], [], [], [], []
            
            for date in cols:
                op = np.nan
                for key in ['Operating Income', 'Operating Revenue']:
                    if key in financials.index and pd.notna(financials.loc[key, date]):
                        op = financials.loc[key, date]
                        break
                if pd.notna(op): op_incomes.append(op)
                
                ord_inc = np.nan
                for key in ['Pretax Income', 'Income Before Tax']:
                    if key in financials.index and pd.notna(financials.loc[key, date]):
                        ord_inc = financials.loc[key, date]
                        break
                if pd.notna(ord_inc): ord_incomes.append(ord_inc)
                
                net = np.nan
                if 'Net Income' in financials.index and pd.notna(financials.loc['Net Income', date]):
                    net = financials.loc['Net Income', date]
                if pd.notna(net): net_incomes.append(net)
                
                year_eps = np.nan
                if 'Basic EPS' in financials.index and pd.notna(financials.loc['Basic EPS', date]):
                    year_eps = financials.loc['Basic EPS', date]
                try:
                    year_str = str(date.year)
                    if not hist_10y.empty and year_str in hist_10y.index.strftime('%Y'):
                        if pd.notna(year_eps) and year_eps > 0:
                            per_history.append(hist_10y.loc[year_str]['Close'].mean() / year_eps)
                except: pass

                bb, dp = 0, 0
                if not cashflow.empty and date in cashflow.columns:
                    for key in ['Repurchase Of Capital Stock', 'Common Stock Repurchased']:
                        if key in cashflow.index and pd.notna(cashflow.loc[key, date]):
                            bb = abs(cashflow.loc[key, date])
                            break
                    for key in ['Cash Dividends Paid', 'Dividends Paid']:
                        if key in cashflow.index and pd.notna(cashflow.loc[key, date]):
                            dp = abs(cashflow.loc[key, date])
                            break
                buybacks.append(bb)
                total_returns.append(bb + dp)
            
            if years_count > 0:
                data["4年赤字率_pct"] = round((sum(1 for x in net_incomes if x < 0) / years_count * 100), 1)
            
            data["4年平均PER_赤字除"] = round(float(np.mean(per_history)), 2) if per_history else data["PER"]
            
            avg_bb = float(np.mean(buybacks)) / 100000000 if buybacks else 0
            avg_tr = float(np.mean(total_returns)) / 100000000 if total_returns else 0
            data["4年平均自社株買い_億"] = round(avg_bb, 1)
            data["4年平均総還元額_億"] = round(avg_tr, 1)
            
            if avg_mc_4y > 0:
                data["4年自社株買い利回り_pct"] = round(avg_bb / avg_mc_4y * 100, 2)
                data["4年平均還元利回り_pct"] = round(avg_tr / avg_mc_4y * 100, 2)
            if avg_tr > 0: 
                data["4年自社株買い比率_pct"] = round(avg_bb / avg_tr * 100, 1)
            
            if op_incomes: data["4年最低営業利益_億"] = round(float(min(op_incomes)) / 100000000, 1)
            if ord_incomes: data["4年最低経常利益_億"] = round(float(min(ord_incomes)) / 100000000, 1)
    except: pass
    return data

# ==========================================
# 5. Firebase連携とメイン処理
# ==========================================
def initialize_firebase():
    if not firebase_admin._apps:
        if FIREBASE_CREDENTIALS:
            cred = credentials.Certificate(json.loads(FIREBASE_CREDENTIALS))
        else:
            cred = credentials.Certificate(FIREBASE_KEY)
        firebase_admin.initialize_app(cred)
    return firestore.client()

def parse_codes_arg(codes_arg):
    if not codes_arg:
        return None
    codes = re.findall(r'(?<!\d)\d{4}(?!\d)', str(codes_arg))
    if not codes:
        raise ValueError(f"銘柄コードを4桁で指定してください: {codes_arg}")
    return sorted(set(codes))

def validate_tag_mapping():
    unknown_categories = sorted(set(TAG_MAPPING.values()) - set(DISPLAY_ORDER))
    if unknown_categories:
        joined = ", ".join(unknown_categories)
        raise ValueError(f"TAG_MAPPINGにDISPLAY_ORDER未定義のカテゴリがあります: {joined}")

def get_all_listed_codes():
    url = "https://www.jpx.co.jp/markets/statistics-equities/misc/tvdivq0000001vg2-att/data_j.xls"
    print("JPXから上場銘柄リストを取得中...")
    try:
        res = requests.get(url, timeout=10)
        df = pd.read_excel(io.BytesIO(res.content))
        
        # ETF, REIT などを除外（普通株式のみにフィルタリング）
        invalid_markets = ["ETF・ETN", "REIT・ベンチャーファンド・カントリーファンド・インフラファンド", "出資証券"]
        df = df[~df['市場・商品区分'].isin(invalid_markets)]
        
        companies = []
        for i, row in df.iterrows():
            code = str(row['コード']).strip()
            name = str(row['銘柄名']).strip()
            market = str(row['市場・商品区分']).strip()
            sector = str(row['33業種区分']).strip()
            if len(code) >= 4:
                companies.append({"code": code[:4], "name": name, "market": market, "sector": sector})
                
        return companies
    except Exception as e:
        print(f"上場銘柄リストの取得に失敗しました: {e}")
        return []

def main():
    print("=== 全データ統合バッチ処理（原点回帰 ＆ 有価証券追加版） ===")
    
    parser = argparse.ArgumentParser(description="Stock Data Scraper")
    parser.add_argument("--total-shards", type=int, default=1, help="Total number of shards")
    parser.add_argument("--shard-index", type=int, default=0, help="Index of this shard (0 to total-shards-1)")
    parser.add_argument("--codes", type=str, default="", help="Comma or space separated stock codes. Example: --codes 7203,6758")
    parser.add_argument("--days-back", type=int, default=365, help="How many days of EDINET documents to scan")
    parser.add_argument("--debug-bs", action="store_true", help="Write B/S extraction diagnostics JSON for each processed code")
    parser.add_argument("--debug-dir", type=str, default=".", help="Directory for --debug-bs output files")
    parser.add_argument("--dry-run", action="store_true", help="Run without writing results to Firestore")
    args = parser.parse_args()

    if not EDINET_API_KEY:
        raise RuntimeError("EDINET_API_KEY が未設定です。環境変数またはGitHub Secretsに設定してください。")
    if args.total_shards < 1:
        raise ValueError("--total-shards は1以上で指定してください。")
    if args.shard_index < 0 or args.shard_index >= args.total_shards:
        raise ValueError("--shard-index は 0 以上 total-shards 未満で指定してください。")

    validate_tag_mapping()
    requested_codes = parse_codes_arg(args.codes)
    if not args.dry_run and not requested_codes and not ALLOW_FULL_FIRESTORE_WRITE:
        raise RuntimeError(
            "全件Firestore更新は安全のためブロックされました。"
            "全件更新を許可する場合は ALLOW_FULL_FIRESTORE_WRITE=1 を設定してください。"
        )
    
    # Firebase接続
    collection_ref = None
    if args.dry_run:
        print("DRY RUN: Firestoreへの保存をスキップします。")
    else:
        db = initialize_firebase()
        collection_ref = db.collection('companies')

    companies_list = get_all_listed_codes()
    
    if not companies_list:
        print("エラー: 銘柄リストが取得できなかったため、処理を終了します。")
        return

    jpx_codes = {c["code"]: c for c in companies_list}

    if requested_codes:
        companies_list = [
            jpx_codes.get(code, {"code": code, "name": "名称不明(指定銘柄)", "market": "不明", "sector": "不明"})
            for code in requested_codes
        ]
        target_codes_for_scan = requested_codes
        print(f"\n単体更新モード: {', '.join(requested_codes)} のみ更新します。")
    else:
        # 先にEdinetSearcherで過去書類をスキャンし、東証以外の銘柄を洗い出す
        target_codes_for_scan = list(jpx_codes.keys()) + ["0000"] # 確実に365日スキャンさせるためのダミーコード
    
    searcher = EdinetSearcher()
    searcher.fetch_list(target_codes_for_scan, days_back=args.days_back)
    
    if not requested_codes:
        # EDINETで見つかった全証券コードを抽出
        edinet_sec_codes = set()
        if not searcher.df_docs.empty:
            for sec in searcher.df_docs['secCode'].dropna().unique():
                sec_str = str(sec).strip()
                # 一般事業会社の証券コードは5桁で末尾が0
                if len(sec_str) == 5 and sec_str.endswith('0'):
                    edinet_sec_codes.add(sec_str[:4])
                    
        # JPXリストにないEDINET提出企業（主に地方単独上場）を追加
        added_count = 0
        for code in edinet_sec_codes:
            if code not in jpx_codes:
                companies_list.append({"code": code, "name": "名称不明(東証以外)", "market": "その他市場", "sector": "その他"})
                added_count += 1
                
        print(f"\nJPXリストにない地方上場企業などを {added_count} 社追加しました。")

    target_codes = [c["code"] for c in companies_list]
    info_dict = {c["code"]: c for c in companies_list}
    
    # 分散処理のためのスライス計算
    target_codes = sorted(target_codes)  # 順序を固定するためソート
    total_len = len(target_codes)
    
    if args.total_shards > 1 and not requested_codes:
        start_idx = total_len * args.shard_index // args.total_shards
        end_idx = total_len * (args.shard_index + 1) // args.total_shards
        target_codes = target_codes[start_idx:end_idx]
        print(f"\n分散処理が有効です: Shard {args.shard_index + 1} / {args.total_shards}")
        print(f"全体 {total_len}社のうち、{len(target_codes)}社を処理します（インデックス {start_idx}〜{end_idx-1}）")
        
    total_count = len(target_codes)
    print(f"\n取得対象銘柄数 (本Shard): {total_count}社")
    if requested_codes:
        print("※単体更新モードのため、Shard指定は無視します。")
    else:
        print("※分散処理のため、各Shardごとに並行して処理が行われます。")

    for i, code in enumerate(target_codes, 1):
        print(f"\n[{i}/{total_count}] {code} 処理中...")
        comp_info = info_dict.get(code, {})
        company_name = comp_info.get("name", "名称不明")
        market = comp_info.get("market", "")
        sector = comp_info.get("sector", "")
        
        # ★ 東証以外の企業など情報の無い銘柄は、みんかぶから企業名等を補完
        if "不明" in company_name or "東証以外" in company_name:
            try:
                url_mk = f"https://minkabu.jp/stock/{code}"
                res_mk = requests.get(url_mk, headers={'User-Agent': 'Mozilla/5.0'}, timeout=5)
                if res_mk.status_code == 200:
                    soup_mk = BeautifulSoup(res_mk.text, 'html.parser')
                    
                    # 企業名
                    t_title = soup_mk.find('title')
                    if t_title:
                        scraped_name = t_title.text.split(' (')[0].strip()
                        if scraped_name: company_name = scraped_name
                    
                    # 市場
                    m_label = soup_mk.find('div', class_='stock_label')
                    if m_label:
                        market = m_label.text.replace(chr(160), ' ').replace(str(code), '').strip()
                        
                    # 業種
                    for el in soup_mk.find_all(string=re.compile('業種')):
                        if el.strip() == "業種":
                            nx = el.parent.find_next_sibling()
                            if nx:
                                sector = nx.text.strip()
                                break
            except Exception as e:
                print(f" -> [警告] みんかぶからの情報補完に失敗しました: {e}")

        try:
            combined_data = {k: 0 for k in DISPLAY_ORDER}
            combined_data.update({
                "★企業名": company_name,
                "★市場区分": market,
                "★業種": sector,
                "★資産合計": 0, "★負債合計": 0, "★純資産合計": 0,
                "不動産_簿価_億": 0, "不動産_時価_億": 0, "不動産_含み益_億": 0, "有価証券_含み益_億": 0,
                "B/S_取得書類": "なし", "不動産_取得書類": "なし"
            })
            
            fin_data = get_financial_data(code)
            combined_data.update(fin_data)
            
            # B/S データの取得
            bs_doc_id, bs_desc, _ = searcher.find_best_bs_doc(code)
            if bs_doc_id:
                ret = analyze_bs_xbrl(bs_doc_id, debug=args.debug_bs)
                if ret:
                    bs_diagnostics = None
                    if len(ret) == 5:
                        summary, totals, doc_type, _, bs_diagnostics = ret
                        combined_data["B/S_取得書類"] = f"{bs_desc} ({doc_type})"
                    elif len(ret) == 4: # To handle new signature safely
                        summary, totals, doc_type, _ = ret
                        combined_data["B/S_取得書類"] = f"{bs_desc} ({doc_type})"
                    elif len(ret) == 3:
                        summary, totals, doc_type = ret
                        combined_data["B/S_取得書類"] = f"{bs_desc} ({doc_type})"
                    else:
                        summary, totals = ret
                        combined_data["B/S_取得書類"] = bs_desc
                        
                    for k in DISPLAY_ORDER:
                        combined_data[k] = round(summary[k] / 100000000, 3)
                    combined_data["★資産合計"] = round(totals['Assets'] / 100000000, 3)
                    combined_data["★負債合計"] = round(totals['Liabilities'] / 100000000, 3)
                    combined_data["★純資産合計"] = round(totals['NetAssets'] / 100000000, 3)

                    if bs_diagnostics:
                        warnings_text = bs_diagnostics.get("warnings", [])
                        combined_data["B/S_警告"] = warnings_text
                        os.makedirs(args.debug_dir, exist_ok=True)
                        debug_path = os.path.join(args.debug_dir, f"debug_bs_{code}.json")
                        with open(debug_path, "w", encoding="utf-8") as f:
                            json.dump(bs_diagnostics, f, ensure_ascii=False, indent=2)
                        print(f" -> [B/S診断] {debug_path} に出力しました。警告: {len(warnings_text)}件")
            
            time.sleep(2)  # API制限対策・待機
            
            # 不動産と有価証券データの取得
            re_doc_id = searcher.find_best_re_doc(code)
            if re_doc_id:
                re_sec_data = analyze_real_estate_and_securities_html(re_doc_id)
                if re_sec_data["不動産_時価_億"] > 0 or re_sec_data["不動産_簿価_億"] > 0 or re_sec_data["有価証券_含み益_億"] > 0:
                    combined_data.update(re_sec_data)
                    combined_data["不動産_取得書類"] = "有価証券報告書等より取得"

            # Firebaseへ保存
            if args.dry_run:
                print(" -> [DRY RUN] Firestore保存をスキップしました。")
            else:
                combined_data["データ最終更新日"] = firestore.SERVER_TIMESTAMP
                collection_ref.document(str(code)).set(combined_data, merge=True)
            
            print(f" -> [{company_name}] 財務 ROE: {combined_data['ROE_pct']}% / 時価総額: {combined_data['時価総額_億']}億円 / 4年平均自社株買い: {combined_data['4年平均自社株買い_億']}億円")
            print(f" -> [ B/S] 資産合計: {combined_data['★資産合計']}億円 ({combined_data['B/S_取得書類']})")
            print(f" -> [隠し資産] 不動産含み益: {combined_data['不動産_含み益_億']}億円 / 有価証券含み益: {combined_data['有価証券_含み益_億']}億円")
            
        except Exception as e:
            print(f" -> [エラー] {code} の処理中にエラーが発生しました: {e}")
            
        time.sleep(2)  # API制限対策・次の銘柄へ行く前に待機

    print("\nすべての処理が完了しました！")

if __name__ == "__main__":
    main()
